
```{r}
library(tidyverse)
library(synExtra)
library(fst)
library(data.table)
library(powerjoin)

synapser::synLogin()

syn <- synDownloader("~/data", .cache = TRUE)
```

```{r}
kinomescan_pseudo_ic50s <- syn("syn51080578") %>%
    read_csv()

kinomescan_classes <- syn("syn51080579") %>%
    read_csv()

# kinomescan_kinase_info <- syn("syn51286743") %>%
#     read_csv()

# single_dose <- syn("syn26486828") %>%
#     read_csv()

lsp_biochem <- syn("syn25173511") %>%
  read_fst()
lsp_targets <- syn("syn25173506") %>%
  read_fst()
```


```{r pseudo_ic50_plots}

pseudo_ic50_class <- kinomescan_pseudo_ic50s %>%
  power_full_join(
    kinomescan_classes %>%
      select(lspci_id, `DiscoveRx Gene Symbol`, classification) %>%
      mutate(
        classification = factor(
          classification,
          levels = c("binding", "weakly-binding", "undetermined", "non-binding")
        )
      ),
    by = c("lspci_id", "DiscoveRx Gene Symbol"),
    check = check_specs(
      duplicate_keys_left = "abort",
      duplicate_keys_right = "abort",
      unmatched_keys_left = "abort",
      unmatched_keys_right = "abort"
    )
  ) %>%
  power_left_join(
    lsp_targets %>%
      filter(organism == "Homo sapiens") %>%
      select(lspci_target_id, symbol),
    by = c("Entrez Gene Symbol" = "symbol"),
    check = check_specs(
      duplicate_keys_left = "ignore",
      duplicate_keys_right = "ignore",
      unmatched_keys_left = "warn",
      unmatched_keys_right = "ignore"
    )
  )

pseudo_ic50_comp <- pseudo_ic50_class %>%
  group_by(
    lspci_id, hmsl_id, `Entrez Gene Symbol`, lspci_target_id
  ) %>%
  arrange(classification == "discordant", pseudo_ic50_relation != "=", pseudo_ic50) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  inner_join(
    lsp_biochem,
    by = c("lspci_id", "lspci_target_id")
  )

p <- pseudo_ic50_comp %>%
  filter(
    # pseudo_ic50_relation == "=",
    classification != "discordant"
  ) %>%
  ggplot(
    # aes(value, pseudo_ic50, color = classification, shape = pseudo_ic50_relation)
    aes(value, pseudo_ic50, color = classification)
  ) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  scale_y_log10() +
  labs(
    x = "IC50 (ChEMBL)",
    y = "Pseudo-IC50 (KINOMEscan)"
  )

ggsave(
    "plots/chembl_ic50_vs_kinomescan_pseudo_ic50.pdf", p,
    width = 10, height = 7
)

library(ggbeeswarm)
p <- pseudo_ic50_comp %>%
  filter(
    # pseudo_ic50_relation == "=",
    classification != "discordant"
  ) %>%
  ggplot(
    aes(value, classification, color = classification)
  ) +
  geom_quasirandom(groupOnX = FALSE) +
  geom_boxplot(fill = NA) +
  scale_x_log10() +
  labs(x = "IC50 (ChEMBL)", y = NULL)

ggsave(
    "plots/chembl_ic50_by_kinomescan_class_beeswarm.pdf", p,
    width = 7, height = 3
)

pseudo_ic50_comp %>%
  filter(
    pseudo_ic50_relation == "=",
    classification != "discordant"
  ) %>%
  group_by(classification) %>%
  mutate(ic50 = value) %>%
  summarize(
    across(
      c(pseudo_ic50, ic50),
      list(
        # average = ~10^(mean(log10(.x))),
        # ci = ~list(10^DescTools::MeanCI(log10(.x)))
        ci = ~list(10^quantile(log10(.x), c(.05, .5, .95)))
      )
    ),
    .groups = "drop"
  ) %>%
  unnest_wider(ends_with("ci"), names_sep = "_")


pseudo_ic50_comp_left <- pseudo_ic50_class %>%
  group_by(
    lspci_id, hmsl_id, `Entrez Gene Symbol`, lspci_target_id
  ) %>%
  arrange(classification == "discordant", pseudo_ic50_relation != "=", pseudo_ic50) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  left_join(
    lsp_biochem,
    by = c("lspci_id", "lspci_target_id")
  )

pseudo_ic50_comp_left %>%
  mutate(
    chembl_is_covered = !is.na(value)
  ) %>%
  count(chembl_is_covered)


```

```{r ic50_single_dose_comp}

single_dose_comp <- single_dose_trans %>%
  power_left_join(
    lsp_targets %>%
      filter(organism == "Homo sapiens") %>%
      select(lspci_target_id, symbol),
    by = c("Entrez Gene Symbol" = "symbol"),
    check = check_specs(
      duplicate_keys_left = "ignore",
      duplicate_keys_right = "ignore",
      unmatched_keys_left = "warn",
      unmatched_keys_right = "ignore"
    )
  ) %>%
  inner_join(
    lsp_biochem,
    by = c("lspci_id", "lspci_target_id")
  )


ps <- single_dose_comp %>%
  mutate(
    percent_control_zero = `Percent Control` == 0,
    percent_control_trans = if_else(
      percent_control_zero,
      0.5 * min(`Percent Control`[`Percent Control` > 0]),
      `Percent Control`
    ),
    value = pmin(value, 30000)
  ) %>%
  filter(!qpcr_miss) %>%
  group_by(`Compound Concentration (nM)`) %>%
  summarize(
    plot = list(
      # ggplot(cur_data(), aes(value, percent_control_trans, shape = percent_control_zero)) +
      ggplot(cur_data(), aes(value, `Percent Control`)) +
        geom_point(alpha = 0.5) +
        # scale_shape_manual(
        #   values = c(`TRUE` = 25, `FALSE` = 16)
        # ) +
        scale_x_log10(breaks = c(0.1, 1, 10, 100, 1000, 10000), labels = scales::label_number()) +
        # scale_y_log10() +
        guides(shape = "none") +
        labs(
          x = "IC50 ChEMBL (nM)",
          y = "% control Eurofins",
          title = paste("Compound concentration", cur_group()$`Compound Concentration (nM)`, "nM")
        )
    )
  )

pwalk(
  ps,
  function(`Compound Concentration (nM)`, plot, ...) {
    ggsave(
      paste0("plots/single_dose_vs_chembl_ic50_", `Compound Concentration (nM)`, "nM.pdf"),
      plot,
      width = 8, height = 8
    )
  }
)
```


```{r upload_synapse}
synStoreMany(
  c(
    "classification/okl_eurofins_pseudo_ic50.csv",
    "classification/okl_eurofins_classification.csv"
  ),
  parentId = "syn18508401",
  used = unname(inputs),
  executed = "https://github.com/labsyspharm/okl-analysis/blob/main/okl_descriptive.Rmd",
  forceVersion = FALSE
)

```
