---
title: "Analysis of "
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(synExtra)
library(here)
library(fst)
library(data.table)
library(powerjoin)
library(qs)
# library(dtplyr)

theme_set(theme_minimal())

synapser::synLogin()
syn <- synDownloader("~/data/", .cache = TRUE)
```

```{r loading}
inputs <- list(
  okl_single_dose_datasets = "syn52504516",
  kinase_info = "syn51286743",
  okl_kds = "syn69680641",
  partition_index_max = "syn52576129",
  okl_metadata = "syn63303526"
)

input_files <- map(
  inputs, syn
)

single_dose <- input_files[["okl_single_dose_datasets"]] %>%
  read_csv() %>%
  filter(dataset == "original_repeat_replaced")

kinase_info <- input_files[["kinase_info"]] %>%
  read_csv() %>%
  filter(`DiscoveRx Gene Symbol` %in% single_dose$`DiscoveRx Gene Symbol`)

mutant_panel <- kinase_info %>%
  mutate(
    mutant = str_detect(`Kinase Form`, "Mutation")
  ) %>%
  filter(mutant) %>%
  bind_rows(
    filter(
      kinase_info,
      `Kinase Form` == "Wild Type",
      hgnc_symbol %in% .$hgnc_symbol
    ) %>%
      mutate(mutant = FALSE)
  )

okl_kds <- input_files[["okl_kds"]] %>%
  fread() %>%
  as_tibble() %>%
  filter(dataset == "original_repeat_replaced")

partition_index_max <- input_files[["partition_index_max"]] %>%
  read_csv() %>%
  filter(dataset == "original_repeat_replaced")

okl_metadata <- input_files[["okl_metadata"]] %>%
  read_csv() %>%
  mutate(
    type_combined = str_remove(type, fixed(" (our ratio)")) %>%
      factor(levels = c("i", "ii", "iii", "iv"))
  )
```


```{r}
okl_kds_dedup <- okl_kds %>%
  filter(
    hgnc_symbol != "",
    classification != "discordant",
    !exclude_target,
    library == "OKL"
  ) %>%
  group_by(lspci_id, hgnc_symbol, `DiscoveRx Gene Symbol`) %>%
  slice_min(
    kd,
    with_ties = FALSE,
    na_rm = TRUE
  ) %>%
  ungroup()

CUTOFFS <- c(100, 1000)
TOP_N <- 15

most_inhibited_raw <- okl_kds_dedup %>%
  group_by(hgnc_symbol, `DiscoveRx Gene Symbol`) %>%
  summarize(
    n_inhibitors = map_int(
      set_names(CUTOFFS),
      ~ sum(kd <= as.numeric(.x), na.rm = TRUE)
    ) %>%
      list(),
    .groups = "drop"
  )

most_inhibited <- most_inhibited_raw %>%
  unnest_longer(n_inhibitors, indices_to = "cutoff", values_to = "n_inhibitors") %>%
  mutate(across(cutoff, as.numeric)) %>%
  arrange(desc(n_inhibitors))

most_inhibited %>%
  count(cutoff, n_inhibitors) %>%
  View()

most_targets_raw <- okl_kds_dedup %>%
  group_by(lspci_id, hmsl_id, library, name) %>%
  summarize(
    n_targets = map_int(
      set_names(CUTOFFS),
      ~ sum(kd <= as.numeric(.x), na.rm = TRUE)
    ) %>%
      list(),
    .groups = "drop"
  )

most_targets <- most_targets_raw %>%
  unnest_longer(n_targets, indices_to = "cutoff", values_to = "n_targets") %>%
  mutate(across(cutoff, as.numeric)) %>%
  arrange(desc(n_targets))
```


```{r}
library(UpSetR)

most_inhibited_inhibitors <- most_inhibited %>%
  group_by(cutoff) %>%
  slice_head(n = TOP_N) %>%
  ungroup() %>%
  inner_join(
    okl_kds_dedup,
    by = c("DiscoveRx Gene Symbol", "hgnc_symbol"),
    relationship = "many-to-many"
  ) %>%
  mutate(
    inhibited = kd <= cutoff
  ) %>%
  group_by(lspci_id, cutoff) %>%
  filter(sum(inhibited) > 0) %>%
  ungroup()

most_inhibited_inhibitors_mats <- most_inhibited_inhibitors %>%
  select(name, lspci_id, `DiscoveRx Gene Symbol`, cutoff, inhibited) %>%
  group_nest(cutoff) %>%
  mutate(
    data = map(
      data,
      \(x) pivot_wider(x, names_from = `DiscoveRx Gene Symbol`, values_from = inhibited, values_fill = FALSE)
    )
  )

```

```{r}
most_inhibited_inhibitors_table <- most_inhibited_inhibitors %>%
  filter(inhibited) %>%
  arrange(cutoff, lspci_id, `DiscoveRx Gene Symbol`) %>%
  group_by(cutoff, lspci_id, name) %>%
  summarize(
    inhibited = list(`DiscoveRx Gene Symbol`),
    .groups = "drop"
  ) %>%
  group_by(cutoff, inhibited) %>%
  summarize(
    names = list(name),
    .groups = "drop"
  ) %>%
  mutate(
    inhibited_str = map_chr(inhibited, \(x) paste(x, collapse = ", ")),
    names_str = map_chr(names, \(x) paste(x, collapse = ", ")),
    n_inhibited = map_int(inhibited, length),
    n_compounds = map_int(names, length)
  ) %>%
  arrange(cutoff, desc(n_inhibited))

write_csv(
  most_inhibited_inhibitors_table %>%
    select(where(negate(is.list))),
  here("data", paste0("top", TOP_N, "_most_inhibited_kinases_inhibitor_overlap_table.csv"))
)
```


```{r}
ps <- most_inhibited_inhibitors_mats %>%
  mutate(
    p = map(
      data,
      \(x) {
        # browser()
        colnames(x) <- str_replace(colnames(x), fixed("JH1domain-"), "")
        ComplexUpset::upset(
          select(x, -name, -lspci_id) %>%
            as.data.frame(),
          colnames(x) %>%
            setdiff(c("name", "lspci_id")),
          min_size = 2,
          name = "Compound targets",
          height_ratio = 1.5,
          width_ratio = .25
        )
      }
    )
  )

pwalk(
  ps,
  function(p, cutoff, ...) {
    ggsave(
      here("plots", paste0("upset_top", TOP_N, "_kinase_targets_cutoff_", cutoff, ".pdf")),
      p, width = 5.5, height = 4
    )
  }
)

```

```{r}
library(seriation)
library(ComplexHeatmap)

clust_fun <- function(m) {
  d <- dist(m, method = "euclidian")
  hclust(d, method = "average") %>%
    reorder(d, method = "olo")
}

most_inhibited_inhibitors_hms <- most_inhibited_inhibitors_mats %>%
  mutate(
    hm = map2(
      data, cutoff,
      \(x, co) {
        m <- select(
          x, -name, -lspci_id
        ) %>%
         as.matrix()
        # m_ <- m[rowSums(m) > 0, ] * 1
        m_ <- m[rowSums(m) > 0, ] %>%
          magrittr::set_colnames(str_replace(colnames(.), fixed("JH1domain-"), ""))
        # browser()
        Heatmap(
          ifelse(m_, "hit", "miss"),
          col = c(hit = "#ec4e4ec1", miss = "#cbd4ff"),
          cluster_columns = clust_fun(t(m_)),
          cluster_rows = clust_fun(m_),
          name = " "
        )
        # pheatmap::pheatmap(
        #   m_,
        #   cluster_cols = clust_fun(t(m_)),
        #   cluster_rows = clust_fun(m_),
        #   main = co
        # )
      }
    )
  )

pwalk(
  most_inhibited_inhibitors_hms,
  function(hm, cutoff, ...) {
    withr::with_pdf(
      here("plots", paste0("upset_top", TOP_N, "_kinase_targets_cutoff_", cutoff, "_heatmap.pdf")),
      print(hm), width = 4, height = 4
    )
  }
)


```



```{r}

library(SuperExactTest)
set_input <- most_inhibited_inhibitors %>%
  filter(inhibited) %>%
  group_by(cutoff, hgnc_symbol) %>%
  summarize(
    inhibs = list(name),
    .groups = "drop"
  ) %>%
  group_by(cutoff) %>%
  summarize(
    data = set_names(inhibs, hgnc_symbol) %>%
      list(),
    .groups = "drop"
  )

set_res <- set_input %>%
  mutate(
    res = map(
      data,
      \(x) SuperExactTest::supertest(x, n = length(unique(pseudo_kds$hgnc_symbol)))
    )
  )

pwalk(
  set_res,
  function(res, cutoff, ...) {
    withr::with_cairo_pdf(
      here("plots", paste0("top", TOP_N, "_inhibited_kinases_inhibitor_overlap_cutoff_", cutoff, ".pdf")),
      plot(
        res,
        Layout = "landscape",
        min.intersection.size = 3,
        degree = c(10, 9, 8),
        sort.by = "size",
        show.expected.overlap = TRUE
        # sort.by = x$overlap.sizes %>%
        #   sort() %>%
        #   magrittr::is_greater_than(5) %>%
        #   names(),
        #   Layout = "landscape",
        #   ke
      ), width = 8, height = 4
    )
  }
)

set_plots <- set_res %>%
  mutate(
    plot = map(
      res,
      \(x) {
        plot(
          x,
          Layout = "landscape",
          min.intersection.size = 3,
          sort.by = "size",
          show.expected.overlap = TRUE
          # sort.by = x$overlap.sizes %>%
          #   sort() %>%
          #   magrittr::is_greater_than(5) %>%
          #   names(),
          #   Layout = "landscape",
          #   ke
        )
      }
    )
  )

```


```{r}
partition_index_max_unique <- partition_index_max %>%
  distinct(name, lspci_id, partition_index)

inhibitors_n_kinases <- most_inhibited_inhibitors %>%
  filter(inhibited) %>%
  group_by(cutoff, lspci_id, name) %>%
  summarize(
    n_kinases = n(),
    .groups = "drop"
  ) %>%
  arrange(cutoff, desc(n_kinases))



ps <- inhibitors_n_kinases %>%
  group_nest(cutoff) %>%
  mutate(
    p = map(
      data,
      \(x) {
        # browser()
        df <- partition_index_max_unique %>%
          semi_join(
            pseudo_kds_dedup,
            by = "lspci_id"
          ) %>%
          left_join(
            x,
            by = c("lspci_id", "name")
          ) %>%
          mutate(
            n_kinases = n_kinases %>%
              replace_na(0) %>%
              as.character() %>%
              fct_inseq(ordered = TRUE),
            name = factor(name, levels = name[order(partition_index)])
          )
        ggplot(
          df,
          aes(
            x = name,
            y = partition_index,
            fill = n_kinases
          )
        ) +
          geom_step(group = 1) +
          geom_col(
            aes(
              y = 0.05
            ),
            data = \(y) filter(y, as.numeric(as.character(n_kinases)) > 0)
          ) +
          scale_fill_viridis_d(
            drop = FALSE
          ) +
          scale_color_viridis_d(
            aesthetics = "segment.color",
            drop = FALSE
          ) +
          ggrepel::geom_text_repel(
            aes(
              label = name,
              segment.color = n_kinases,
              # fill = n_kinases,
              y = .05
            ),
            data = \(y) filter(y, as.numeric(as.character(n_kinases)) > 7),
            color = "black",
            direction = "x",
            size = 2.5,
            vjust = 1,
            hjust = 1,
            nudge_y = .6,
            angle = 90,
            seed = 42,
            max.overlaps = 100,
            show.legend = FALSE
          ) +
          theme(
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            panel.grid.major.x = element_blank(),
          )
      }
    )
  )

pwalk(
  ps,
  function(p, cutoff, ...) {
    ggsave(
      here("plots", paste0("top", TOP_N, "_inhibited_kinases_inhibitor_overlap_size_cutoff_", cutoff, ".pdf")),
      p, width = 8, height = 4
    )
  }
)

```


```{r}

pseudo_kds_inhibited <- pseudo_kds_dedup %>%
  crossing(threshold = CUTOFFS) %>%
  filter(pseudo_kd <= threshold)

write_csv(
  pseudo_kds_inhibited %>%
    filter(threshold == 1000),
  here("data", "pseudo_kds_inhibited_1000_threshold.csv")
)


pseudo_kds_n_inhibited <- pseudo_kds_inhibited %>%
  group_by(lspci_id, threshold) %>%
  summarize(
    n_inhibited = n(),
    .groups = "drop"
  )

pseudo_kds_inhibited %>%
  filter(threshold == 1000) %>%
  group_by(hgnc_symbol) %>%
  summarize(
    n = n(),
    .groups = "drop"
  ) %>%
  pull(n) %>%
  paste(collapse = ", ") %>%
  clipr::write_clip()

pseudo_kds_n_inhibited %>%
  filter(threshold == 1000) %>%
  pull(n_inhibited) %>%
  paste(collapse = ", ") %>%
  clipr::write_clip()
```

```{r}
pulp_inputs <- list(
  most_inhibited = most_inhibited,
  most_targets = most_targets
) %>%
  imap(\(x, y) group_nest(x, cutoff, .key = paste0(y, "_data"))) %>%
  reduce(left_join, by = "cutoff") %>%
  mutate(
    pulp_output = here("data", paste("random_matrices_cutoff", cutoff, "nM.csv", sep = "_"))
  )

library(processx)

pulp_python <- "/opt/miniconda3/envs/pulp/bin/python"

pulp_output <- run(
  pulp_python,
  args = c(
    here("generate_binary_matrix.py"),
    "--n_matrices", 5,
    "--rows", paste(pulp_inputs$most_inhibited_data[[1]]$n_inhibitors, collapse = ", "),
    "--columns", paste(pulp_inputs$most_targets_data[[1]]$n_targets, collapse = ", "),
    "--output", pulp_inputs$pulp_output[[1]],
    "--max_workers", 8
  ),
  echo = TRUE
)

x <- read_csv(pulp_inputs$pulp_output[[1]])

pulp_outputs <- pulp_inputs %>%
  mutate(
    pulp_output = pmap(
      .,
      \(most_inhibited_data, most_targets_data, pulp_output, ...) {
        run(
          pulp_python,
          args = c(
            here("generate_binary_matrix.py"),
            "--n_matrices", 1000,
            "--rows", paste(most_inhibited_data$n_inhibitors, collapse = ", "),
            "--columns", paste(most_targets_data$n_targets, collapse = ", "),
            "--output", pulp_output,
            "--max_workers", 8
          ),
          echo = TRUE
        )
        read_csv(pulp_output)
      }
    )
  )

qsave(
  pulp_outputs,
  here("data", "random_matrices.qs")
)
```


```{r}
pulp_outputs_long <- pulp_outputs %>%
  mutate(
    pulp_output = pmap(
      .,
      \(most_inhibited_data, most_targets_data, pulp_output, ...) {
        mutate(
          pulp_output,
          `DiscoveRx Gene Symbol` = most_inhibited_data$`DiscoveRx Gene Symbol`[Row + 1],
          lspci_id = most_targets_data$lspci_id[Col + 1],
        )
      }
    )
  ) %>%
  select(cutoff, pulp_output) %>%
  unnest(pulp_output)

```


```{r}
pulp_top15_together <- pulp_outputs_long %>%
  semi_join(
    most_inhibited %>%
      arrange(desc(n_inhibitors)) %>%
      group_by(cutoff) %>%
      slice_head(n = TOP_N) %>%
      ungroup(),
    by = c("DiscoveRx Gene Symbol", "cutoff")
  ) %>%
  count(
    cutoff, Matrix, lspci_id
  )

real_top15_together <- pseudo_kds_dedup %>%
  crossing(cutoff = CUTOFFS) %>%
  filter(pseudo_kd <= cutoff) %>%
  semi_join(
    most_inhibited %>%
      arrange(desc(n_inhibitors)) %>%
      group_by(cutoff) %>%
      slice_head(n = TOP_N) %>%
      ungroup(),
    by = c("DiscoveRx Gene Symbol", "cutoff")
  ) %>%
  count(
    cutoff, lspci_id, name
  )

real_and_pulp_top15_together <- bind_rows(
  real_top15_together %>%
    mutate(Matrix = -1) %>%
    select(-name),
  pulp_top15_together
)
```


```{r}
p <- real_and_pulp_top15_together %>%
  group_by(
    n_kinases = n,
    cutoff, Matrix
  ) %>%
  summarize(
    n_inhibitors = n(),
    .groups = "drop"
  ) %>%
  ggplot(
    aes(fct_inseq(as.character(n_kinases)), n_inhibitors)
  ) +
  ggbeeswarm::geom_quasirandom(
    dodge.width = .5,
    alpha = 0.5, orientation = "x",
    shape = 16,
    data = \(x) filter(x, Matrix >= 0)
  ) +
  geom_point(
    data = \(x) filter(x, Matrix == -1),
    size = 3,
    shape = 16,
    color = "red"
  ) +
  facet_wrap(~cutoff) +
  # geom_text(
  #   aes(label = signif(p, 2)),
  #   y = Inf,
  #   vjust = 1,
  #   data = random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group_p
  # ) +
  labs(
    x = "Number of top 15 kinases hit",
    y = "Number of inhibitors"
  )

ggsave(
  here("plots", "overlap_stats_real_and_pulp_top15_together_raw_distribution.pdf"),
  p, width = 8, height = 4
)
```



```{r}
overlap_stats_real_and_pulp_top15_together <- real_and_pulp_top15_together %>%
  mutate(
    over = choose(n, 2)
  ) %>%
  group_by(
    cutoff, Matrix
  ) %>%
  summarize(
    over_sum = sum(over),
    .groups = "drop"
  )

overlap_stats_real_and_pulp_top15_together_p <- overlap_stats_real_and_pulp_top15_together %>%
  group_by(cutoff) %>%
  summarize(
    p = (1 + sum(over_sum[Matrix == -1] <= over_sum[Matrix >= 0])) / (n() + 1),
    .groups = "drop"
  )

p <- overlap_stats_real_and_pulp_top15_together %>%
  ggplot(
    aes(fct_inseq(as.character(cutoff)), over_sum)
  ) +
  ggbeeswarm::geom_quasirandom(
    # dodge.width = .5,
    alpha = 0.5,
    orientation = "x",
    shape = 16,
    data = \(x) filter(x, Matrix >= 0)
  ) +
  geom_point(
    data = \(x) filter(x, Matrix == -1),
    size = 3,
    shape = 16,
    color = "red"
  ) +
  geom_text(
    aes(label = paste("p =", signif(p, 2))),
    y = Inf,
    vjust = 1,
    hjust = .5,
    data = overlap_stats_real_and_pulp_top15_together_p
  ) +
  labs(
    x = "Kd cutoff",
    y = "Pairwise co-inhibition count"
  )
p

ggsave(
  here("plots", "overlap_stats_real_and_pulp_top15_together.pdf"),
  p, width = 3, height = 3
)
```

```{r}
hgnc_id_map <- pseudo_kds_inhibited %>%
  filter(threshold == 1000) %>%
  group_by(hgnc_symbol) %>%
  summarize(
    n = n(),
    .groups = "drop"
  ) %>%
  select(hgnc_symbol) %>%
  mutate(
    id = seq_len(n()) - 1
  )

lspci_id_map <- pseudo_kds_n_inhibited %>%
  filter(threshold == 1000) %>%
  select(lspci_id) %>%
  mutate(
    id = seq_len(n()) - 1
  )

random_matrices_1000_threshold <- syn("syn54155262") %>%
  read_csv() %>%
  magrittr::set_colnames(c("matrix_id", "row_id", "col_id")) %>%
  power_inner_join(
    hgnc_id_map,
    by = c("row_id" = "id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      unmatched_keys_right = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  power_inner_join(
    lspci_id_map,
    by = c("col_id" = "id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      unmatched_keys_right = "warn",
      duplicate_keys_right = "warn"
    )
  )

random_and_real_1000_threshold <- bind_rows(
  pseudo_kds_inhibited %>%
    filter(threshold == 1000) %>%
    transmute(matrix_id = -1, lspci_id, hgnc_symbol),
  random_matrices_1000_threshold
)

pseudo_kds_inhibited_n_inhibs_per_kinase <- pseudo_kds_inhibited %>%
  count(threshold, hgnc_symbol) %>%
  arrange(threshold, desc(n))

top_15_1000 <- pseudo_kds_inhibited_n_inhibs_per_kinase %>%
  filter(threshold == 1000) %>%
  slice_head(n = 15)

random_and_real_1000_n_overlap_top_15_kinases <- random_and_real_1000_threshold %>%
  filter(hgnc_symbol %in% top_15_1000$hgnc_symbol) %>%
  count(matrix_id, lspci_id, name = "n_kinases")


random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group <- random_and_real_1000_n_overlap_top_15_kinases %>%
  count(matrix_id, n_kinases, name = "n_inhibitors") %>%
  complete(matrix_id, n_kinases, fill = list(n_inhibitors = 0))

p <- random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group %>%
  filter(matrix_id >= 0) %>%
  ggplot(
    aes(fct_inseq(as.character(n_kinases)), n_inhibitors)
  ) +
  ggbeeswarm::geom_quasirandom(
    dodge.width = .5,
    alpha = 0.5, orientation = "x"
  ) +
  geom_point(
    data = filter(random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group, matrix_id == -1),
    size = 4,
    color = "red"
  ) +
  geom_text(
    aes(label = signif(p, 2)),
    y = Inf,
    vjust = 1,
    data = random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group_p
  ) +
  labs(
    x = "Number of top 15 kinases hit",
    y = "Number of inhibitors"
  )

ggsave(
  here("plots", "top_15_kinases_n_inhibitors.pdf"),
  p, width = 8, height = 4
)

random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group_p <- random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group %>%
  filter(matrix_id >= 0) %>%
  inner_join(
    random_and_real_1000_n_overlap_top_15_kinases_n_inhibs_per_group %>%
      filter(matrix_id == -1) %>%
      select(n_kinases, n_inhibitors_real = n_inhibitors),
    by = "n_kinases"
  ) %>%
  group_by(n_kinases) %>%
  summarize(p = sum(n_inhibitors >= n_inhibitors_real) / n(), .groups = "drop")

```

Heatmap of mutant panel

```{r}
library(ComplexHeatmap)
library(seriation)
library(impute)

cluster_fun_eucl <- function(mat, sample_in_col = TRUE) {
  if (!sample_in_col) {
    mat <- t(mat)
  }
  mat_imp <- impute.knn(
    mat, rng.seed = 42
  )[["data"]]
  if (!sample_in_col) {
    mat_imp <- t(mat_imp)
    mat <- t(mat)
  }
  # browser()
  dist_mat <- dist(mat_imp)
  # dist_mat <- as.dist(mat)
  clust <- hclust(dist_mat, method = "average")
  reorder(clust, dist_mat, method = "OLO")
}


createAnnotation <- function(df, colors = list(), which = "column") {
  # Load necessary libraries
  color_maps <- list()

  # Iterate over each column in the dataframe
  for (col_name in names(df)) {
    # Check if the column is numeric
    if (is.numeric(df[[col_name]])) {
      # Create a color mapping function for numeric columns
      if (is.null(colors[[col_name]]))
        colors[[col_name]] <- c("white", "red")
      if (is.function(colors[[col_name]])) {
        col_fun <- colors[[col_name]]
      } else if (is.character(colors[[col_name]])) {
        n <- length(colors[[col_name]])
        if (n == 1) {
          col_fun <- circlize::colorRamp2(
            seq(from = min(df[[col_name]]), to = max(df[[col_name]]), length.out = 100),
            viridis(100, option = colors[[col_name]])
          )
        } else {
          col_fun <- circlize::colorRamp2(
            seq(from = min(df[[col_name]]), to = max(df[[col_name]]), length.out = n),
            colors[[col_name]]
          )
        }
      } else
        stop("Dont know how to handle colors for column ", col_name)
      color_maps[[col_name]] <- col_fun
    } else {
      if (is.character(colors[[col_name]])) {
        color_maps[[col_name]] <- colors[[col_name]]
        next
      }
      col_fun <- colors[[col_name]] %||% rainbow
      # Create a named vector of colors for categorical columns
      values <- df[[col_name]]
      unique_values <- if (is.factor(values)) levels(values) else unique(df[[col_name]])
      named_colors <- setNames(col_fun(length(unique_values)), unique_values)
      color_maps[[col_name]] <- named_colors
    }
  }

  # Combine all annotations
  combined_annotations <- HeatmapAnnotation(df = df, col = color_maps, which = which)

  return(combined_annotations)
}
```

Redo computation with all kinases included, even mutant ones

```{r}
pseudo_kds_dedup_no <- pseudo_kds %>%
  filter(
    hgnc_symbol != "",
    classification != "discordant",
    pseudo_kd_concordant != "discordant",
    library == "OKL"
  ) %>%
  group_by(lspci_id, hgnc_symbol, `DiscoveRx Gene Symbol`) %>%
  slice_min(
    pseudo_kd,
    with_ties = FALSE,
    na_rm = TRUE
  ) %>%
  ungroup()

CUTOFFS <- c(100, 1000)
TOP_N <- 15

most_inhibited_raw_no <- pseudo_kds_dedup_no %>%
  group_by(hgnc_symbol, `DiscoveRx Gene Symbol`) %>%
  summarize(
    n_inhibitors = map_int(
      set_names(CUTOFFS),
      ~ sum(pseudo_kd <= as.numeric(.x), na.rm = TRUE)
    ) %>%
      list(),
    .groups = "drop"
  )

most_inhibited_no <- most_inhibited_raw_no %>%
  unnest_longer(n_inhibitors, indices_to = "cutoff", values_to = "n_inhibitors") %>%
  mutate(across(cutoff, as.numeric)) %>%
  arrange(desc(n_inhibitors))

most_targets_raw_no <- pseudo_kds_dedup_no %>%
  group_by(lspci_id, hmsl_id, library, name) %>%
  summarize(
    n_targets = map_int(
      set_names(CUTOFFS),
      ~ sum(pseudo_kd <= as.numeric(.x), na.rm = TRUE)
    ) %>%
      list(),
    .groups = "drop"
  )

most_targets_no <- most_targets_raw_no %>%
  unnest_longer(n_targets, indices_to = "cutoff", values_to = "n_targets") %>%
  mutate(across(cutoff, as.numeric)) %>%
  arrange(desc(n_targets))
```


```{r}
better_contrast <- function(
  colors1, colors2, threshold = 0
) {
  # browser()
  farver::compare_colour(
    farver::decode_colour(colors1),
    farver::decode_colour(colors2),
    from_space = "rgb",
    method = "cie2000"
  ) %>% {
      .[, 1] < (1 + threshold) * .[, 2]
    } %>%
    if_else(colors2[2], colors2[1])
}

mutant_hm_data <- tibble(
  cutoff = CUTOFFS
) %>%
  mutate(
    hm = map(
      cutoff,
      \(cu) {
        mat <- pseudo_kds_dedup_no %>%
          filter(`DiscoveRx Gene Symbol` %in% mutant_panel$`DiscoveRx Gene Symbol`) %>%
          transmute(`DiscoveRx Gene Symbol`, lspci_id, pseudo_kd = log10(pseudo_kd)) %>%
          pivot_wider(names_from = lspci_id, values_from = pseudo_kd) %>%
          column_to_rownames("DiscoveRx Gene Symbol") %>%
          as.matrix()
        mutant_panel_sub <- mutant_panel %>%
          slice(match(rownames(mat), `DiscoveRx Gene Symbol`))
        row_anno <- mutant_panel %>%
          left_join(
            most_inhibited_no %>%
              filter(cutoff == cu) %>%
              select(`DiscoveRx Gene Symbol`, n_inhibitors),
            by = "DiscoveRx Gene Symbol"
          ) %>%
          select(`DiscoveRx Gene Symbol`, Group, mutant, n_inhibitors) %>%
          slice(match(rownames(mat), `DiscoveRx Gene Symbol`)) %>%
          column_to_rownames("DiscoveRx Gene Symbol")
        col_anno <- most_targets_no %>%
          filter(cutoff == cu) %>%
          select(lspci_id, n_targets) %>%
          slice(match(colnames(mat), lspci_id)) %>%
          column_to_rownames("lspci_id")
        # browser()
        Heatmap(
          mat,
          name = "Pseudo Kd",
          col = viridisLite::viridis(100, direction = -1),
          cluster_columns = cluster_fun_eucl,
          cluster_rows = cluster_fun_eucl,
          row_split = mutant_panel_sub$hgnc_symbol,
          left_annotation = createAnnotation(
            row_anno,
            which = "row",
            colors = list(Group = \(x) RColorBrewer::brewer.pal(x, "Set2"))
          ),
          top_annotation = createAnnotation(
            col_anno,
            which = "column"
          ),
          show_column_names = FALSE,
          # cell_fun = \(j, i, x, y, width, height, fill) {
          #   # browser()
          #   if (!is.na(mat[i, j]) && mat[i, j] < log10(cu))
          #     grid.text("*", x, y, gp = gpar(fontsize = 10, col = better_contrast(fill, c("white", "black"))))
          # }
        )
      }
    )
  )

pwalk(
  mutant_hm_data,
  \(cutoff, hm) {
    withr::with_pdf(
      here("plots", paste0("mutant_panel_pseudo_kd_heatmap_cutoff_", cutoff, ".pdf")),
      print(hm), width = 10, height = 13
    )
  }
)

```

```{r}

mutant_hm_data <- crossing(
  cutoff = CUTOFFS,
  hgnc_symbol = unique(mutant_panel$hgnc_symbol)
) %>%
  mutate(
    hm = map2(
      cutoff, hgnc_symbol,
      \(cu, g) {
        # browser()
        row_anno <- mutant_panel %>%
          filter(hgnc_symbol == g) %>%
          power_left_join(
            most_inhibited_no %>%
              filter(cutoff == cu) %>%
              select(`DiscoveRx Gene Symbol`, n_inhibitors),
            by = "DiscoveRx Gene Symbol",
            check = check_specs(
              unmatched_keys_left = "warn",
              duplicate_keys_left = "warn",
              duplicate_keys_right = "warn"
            )
          ) %>%
          mutate(
            target_name = if_else(mutant, `DiscoveRx Gene Symbol`, str_replace(`DiscoveRx Gene Symbol`, g, "WT")) %>%
              str_remove(paste0("^", g, "-?")) %>%
              str_remove_all("[\\(\\)]") %>%
              str_replace_all(fixed("phosphorylated"), "p")
          )
        col_anno <- pseudo_kds_dedup_no %>%
          filter(
            `DiscoveRx Gene Symbol` %in% mutant_panel$`DiscoveRx Gene Symbol`,
            hgnc_symbol == g
          ) %>%
          group_by(lspci_id) %>%
          filter(sum(pseudo_kd <= cu) >= 1) %>%
          ungroup() %>%
          distinct(name, lspci_id, hmsl_id) %>%
          mutate(cutoff = cu) %>%
          power_left_join(
            select(okl_metadata, hmsl_id = HMSLID, type_combined),
            by = "hmsl_id",
            check = check_specs(
              unmatched_keys_left = "warn",
              duplicate_keys_left = "warn",
              duplicate_keys_right = "warn"
            )
          ) %>%
          power_left_join(
            select(most_targets_no, lspci_id, cutoff, n_targets),
            by = join_by(lspci_id, cutoff),
            check = check_specs(
              unmatched_keys_left = "warn",
              duplicate_keys_left = "warn",
              duplicate_keys_right = "warn"
            )
          )
        mat <- pseudo_kds_dedup_no %>%
          filter(
            `DiscoveRx Gene Symbol` %in% row_anno$`DiscoveRx Gene Symbol`,
            lspci_id %in% col_anno$lspci_id
          ) %>%
          transmute(`DiscoveRx Gene Symbol`, lspci_id, pseudo_kd = log10(pseudo_kd)) %>%
          pivot_wider(names_from = lspci_id, values_from = pseudo_kd) %>%
          column_to_rownames("DiscoveRx Gene Symbol") %>%
          as.matrix()
        # browser()
        subset_mat <- mat[row_anno$`DiscoveRx Gene Symbol`, as.character(col_anno$lspci_id)]
        # browser()
        Heatmap(
          subset_mat,
          name = "Pseudo Kd",
          column_title = g,
          col = viridisLite::viridis(100, direction = -1),
          cluster_columns = cluster_fun_eucl,
          cluster_rows = cluster_fun_eucl,
          row_labels = row_anno$target_name,
          # row_split = mutant_panel_sub$hgnc_symbol,
          left_annotation = createAnnotation(
            row_anno %>%
              select(`DiscoveRx Gene Symbol`, Mutant = mutant, `N inhibitors` = n_inhibitors) %>%
              column_to_rownames("DiscoveRx Gene Symbol"),
            which = "row",
            colors = list(`N inhibitors` = rev(paletteer::paletteer_c("grDevices::Blues 3", 30)))
          ),
          top_annotation = createAnnotation(
            col_anno %>%
              select(lspci_id, `N targets` = n_targets, Type = type_combined) %>%
              column_to_rownames("lspci_id"),
            which = "column",
            colors = list(
              `N targets` = rev(paletteer::paletteer_c("grDevices::Reds 3", 30)),
              Type = \(x) RColorBrewer::brewer.pal(x, "Set2")
            )
          ),
          # column_labels = col_anno$name,
          show_column_names = FALSE,
          width = ncol(subset_mat) * unit(2, "mm"),
          height = nrow(subset_mat) * unit(5, "mm")
        )
      }
    )
  )

pwalk(
  mutant_hm_data,
  \(cutoff, hgnc_symbol, hm) {
    hm <- draw(hm)
    w <- ComplexHeatmap:::width(hm) %>%
      convertX(unit = "inch", valueOnly = TRUE)
    h <- ComplexHeatmap:::height(hm) %>%
      convertY(unit = "inch", valueOnly = TRUE)
    withr::with_pdf(
      here("plots", paste0("mutant_panel_", hgnc_symbol, "_pseudo_kd_heatmap_cutoff_", cutoff, ".pdf")),
      print(hm), width = w, height = h
    )
  }
)

```
