
```{r}
library(tidyverse)
library(synExtra)
library(fst)
library(data.table)
library(powerjoin)

synapser::synLogin()

syn <- synDownloader("~/data", .cache = TRUE)
```

```{r}
klaeger_ic50s <- syn("syn51288931") %>%
    read_csv()

kinomescan_kd_fits <- syn("syn69680641") %>%
  read_csv()

kinomescan_classes <- syn("syn51080579") %>%
    read_csv()

kinomescan_kinase_info <- syn("syn51286743") %>%
    read_csv()

single_dose <- syn("syn26486828") %>%
    read_csv()

chembl_kd_raw <- syn("syn52854574") %>%
  read_csv()
```


```{r}
chembl_kd_all <- chembl_kd_raw %>%
  filter(
    standard_relation == "=" |
      (standard_relation %in% c(">=", ">") & standard_value > 9000)
  )

chembl_kd_all_agg <- chembl_kd_all %>%
  group_by(gene_symbol, lspci_id) %>%
  summarize(
    chembl_kd = quantile(standard_value, 0.25, na.rm = TRUE, names = FALSE) |>
      pmin(10000),
    chembl_kd_relation = paste(sort(unique(standard_relation)), collapse = ""),
    .groups = "drop"
  )

chembl_kd_no_klaeger_agg <- chembl_kd_all %>%
  filter(
    pubmed_id != 29191878
  ) %>%
  group_by(gene_symbol, lspci_id) %>%
  summarize(
    chembl_kd = quantile(standard_value, 0.25, na.rm = TRUE, names = FALSE) |>
      pmin(10000),
    chembl_kd_relation = paste(sort(unique(standard_relation)), collapse = ""),
    .groups = "drop"
  )

```


```{r}
kinomescan_kd_fits_comp <- kinomescan_kd_fits %>%
  filter(
    !exclude_target,
    classification != "discordant"
  ) %>%
  transmute(
    lspci_id, name, Symbol = `Entrez Gene Symbol`,
    kd = pmin(kd, 10000),
    classification
  ) |>
  # aggregate to kinase level by taking the most potent kd per kinase
  group_by(lspci_id, Symbol) %>%
  slice_min(kd, with_ties = FALSE) |>
  ungroup()

klaeger_ic50_comp <- klaeger_ic50s %>%
  transmute(
    lspci_id, Symbol = Name,
    IC50 = pmin(IC50, 10000) |>
      pmax(min(IC50[IC50 > 0], na.rm = TRUE) * 0.5)
  ) %>%
  power_inner_join(
    kinomescan_kd_fits_comp,
    by = c("lspci_id", "Symbol"),
    check = check_specs(
      unmatched_keys_left = "info",
      unmatched_keys_right = "info",
      duplicate_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )

p <- klaeger_ic50_comp %>%
  ggplot(
    # aes(value, pseudo_ic50, color = classification, shape = pseudo_ic50_relation)
    aes(IC50, kd)
  ) +
  geom_point(
    alpha = 0.5,
    shape = 16,
    size = 1
  ) +
  geom_text(
    aes(
      label = paste0("  R = ", signif(r, 2))
    ),
    x = -Inf, y = Inf,
    hjust = 0, vjust = 1,
    data = \(x) tibble(
      r = cor(log10(x$IC50), log10(x$kd), method = "pearson", use = "complete.obs")
    ),
    inherit.aes = FALSE
  ) +
  scale_x_log10(labels = scales::label_number(big.mark = "")) +
  scale_y_log10(labels = scales::label_number(big.mark = "")) +
  coord_equal() +
  labs(
    x = "Kd Klaeger",
    y = "Kd Kinomescan"
  )
ggsave(
    "plots/klaeger_kd_vs_kinomescan_kd.pdf", p,
    width = 3, height = 3
)


```


### Klaeger vs Chembl

```{r}
klaeger_ic50s_vs_chembl <- klaeger_ic50s %>%
  power_inner_join(
    chembl_kd_no_klaeger_agg,
    by = c("lspci_id", "Name" = "gene_symbol"),
    check = check_specs(
      unmatched_keys_left = "info",
      unmatched_keys_right = "info",
      duplicate_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    IC50 = pmin(IC50, 10000) |>
      pmax(min(IC50[IC50 > 0], na.rm = TRUE) * 0.5)
  )

p <- ggplot(
  klaeger_ic50s_vs_chembl,
  aes(IC50, chembl_kd)
) +
  geom_point(
    alpha = 0.5,
    shape = 16,
    size = 1
  ) +
  geom_text(
    aes(
      label = paste0("  R = ", signif(r, 2))
    ),
    x = -Inf, y = Inf,
    hjust = 0, vjust = 1,
    data = \(x) tibble(
      r = cor(log10(x$IC50), log10(x$chembl_kd), method = "pearson", use = "complete.obs")
    ),
    inherit.aes = FALSE
  ) +
  scale_x_log10(labels = scales::label_number(big.mark = "")) +
  scale_y_log10(labels = scales::label_number(big.mark = "")) +
  coord_equal() +
  labs(
    x = "Kd Klaeger",
    y = "Kd Chembl"
  )

p

ggsave(
    "plots/klaeger_kd_vs_chembl_kd.pdf", p,
    width = 3, height = 3
)
```

Make venn diagram of overlap assayed compounds that we have information for
between Klaeger and Kinomescan

```{r}
library(ggvenn)
p <- bind_rows(
    klaeger = klaeger_ic50s %>%
        select(lspci_id),
    kinomescan = kinomescan_pseudo_ic50s %>%
        select(lspci_id),
    .id = "source"
) %>%
    distinct() %>%
    split(.$source) %>%
    map("lspci_id") %>%
    ggvenn(auto_scale = TRUE)
p
```

Check if there are any compounds that are particularly different between
Klaeger and Kinomescan

Also, label false positives (compared to Klaeger) and false negatives
separately

```{r}
klaeger_ic50_comp_stats <- klaeger_ic50_comp %>%
    mutate(
        IC50 = pmax(IC50, min(na.omit(IC50) %>% .[. > 0]) * 0.5),
        log10_ic50 = log10(IC50),
        log10_pseudo_ic50 = log10(pseudo_ic50),
        log_ic50_diff = log10_ic50 - log10_pseudo_ic50,
        diff_greater_than_1 = abs(log_ic50_diff) > 1,
        difference_class = case_when(
            log_ic50_diff > 1 ~ "FP",
            log_ic50_diff < -1 ~ "FN",
            TRUE ~ "concordant"
        )
    )
```


```{r}
stats_per_group <- function(grouped_df) {
    grouped_df %>%
    summarise(
        n = n(),
        n_binding_class = sum(classification == "binding"),
        frac_binding_class = n_binding_class / n,
        n_diff_greater_than_1 = sum(diff_greater_than_1, na.rm = TRUE),
        frac_diff_greater_than_1 = n_diff_greater_than_1 / n,
        mean_log_ic50_diff = mean(log_ic50_diff, na.rm = TRUE),
        sd_log_ic50_diff = sd(log_ic50_diff, na.rm = TRUE),
        n_false_positives = sum(difference_class == "FP", na.rm = TRUE),
        n_false_negatives = sum(difference_class == "FN", na.rm = TRUE),
        frac_false_positives = n_false_positives / n,
        frac_false_negatives = n_false_negatives / n,
        .groups = "drop"
    )
}

klaeger_ic50_comp_stats_per_compound <- klaeger_ic50_comp_stats %>%
    group_by(lspci_id, name) %>%
    stats_per_group()
```

```{r}
library(ggrepel)
p <- klaeger_ic50_comp_stats_per_compound %>%
  ggplot(aes(frac_binding_class, frac_diff_greater_than_1, text = name)) +
    geom_point() +
    # geom_text_repel(
    #   aes(label = name),
    #   data = ~.x %>%
    #     mutate(name = if_else(discordant < 0.04, "", name)),
    #   min.segment.length = 0
    # ) +
    labs(
        x = "Fraction of 'binding' dose-response curves",
        y = "Fraction of pseudo IC50s with >10x difference",
        title = "Per compound"
    )

plotly::ggplotly(p)

ggsave(
    "plots/klaeger_ic50_vs_kinomescan_pseudo_ic50_differences_per_compound.pdf", p,
    width = 6, height = 4
)
```

Now do the same per kinase

```{r}

klaeger_ic50_comp_stats_per_kinase <- klaeger_ic50_comp_stats %>%
    group_by(Symbol) %>%
    summarise(
        n = n(),
        n_binding_class = sum(classification == "binding"),
        frac_binding_class = n_binding_class / n,
        n_diff_greater_than_1 = sum(diff_greater_than_1, na.rm = TRUE),
        fract_diff_greater_than_1 = n_diff_greater_than_1 / n,
        mean_log_ic50_diff = mean(log_ic50_diff, na.rm = TRUE),
        sd_log_ic50_diff = sd(log_ic50_diff, na.rm = TRUE),
        .groups = "drop"
    )
```

```{r}
p <- klaeger_ic50_comp_stats_per_kinase %>%
  ggplot(aes(frac_binding_class, fract_diff_greater_than_1, text = Symbol)) +
    geom_point() +
    # geom_text_repel(
    #   aes(label = name),
    #   data = ~.x %>%
    #     mutate(name = if_else(discordant < 0.04, "", name)),
    #   min.segment.length = 0
    # ) +
    labs(
        x = "Fraction of 'binding' dose-response curves",
        y = "Fraction of pseudo IC50s with >10x difference",
        title = "Per kinase"
    )
ggsave(
    "plots/klaeger_ic50_vs_kinomescan_pseudo_ic50_differences_per_kinase.pdf", p,
    width = 6, height = 4
)
```
