---
title: "Descriptive analysis of OKL affinity data"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(synExtra)
library(here)
library(fst)
library(data.table)
# library(dtplyr)

theme_set(theme_minimal())

synapser::synLogin()
syn <- synDownloader("~/data/", .cache = TRUE)
```

```{r loading}
inputs <- list(
  okl_single_dose = "syn26486828",
  # hmsl_single_dose = "syn26260430",
  # hmsl_single_dose_agg = "syn26260426",
  compound_dictionary = "syn26260332",
  kinase_info = "syn51286743"
  # references = "syn26260402",
  # target_mapping = "syn26260398",
  # target_dictionary = "syn26260394",
  # compound_mapping = "syn26260389"
)

input_files <- map(
  inputs, syn
)

single_dose <- input_files[["okl_single_dose"]] %>%
  fread()

compound_dictionary <- input_files[["compound_dictionary"]] %>%
  read_fst(as.data.table = TRUE)

compound_names <- compound_dictionary %>%
  select(lspci_id, name = pref_name) %>%
  drop_na() %>%
  # lazy_dt() %>%
  group_by(lspci_id) %>%
  slice_head(n = 1) %>%
  ungroup()
  # as_tibble()

qpcr_misses <- syn("syn33531640") %>%
  readxl::read_excel()

kinase_info <- input_files[["kinase_info"]] %>%
  read_csv()
```

```{r}
p <- single_dose %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  ggplot(aes(`Percent Control`, color = as.ordered(`Compound Concentration (nM)`))) +
    geom_freqpoly() +
    scale_color_viridis_d(direction = -1) +
    labs(color = "Concentration")
ggsave("all_combs_percent_control_hist.pdf", p, width = 5, height = 3)
```


```{r}
single_dose %>%
  count(hmsl_id, `DiscoveRx Gene Symbol`, `Compound Concentration (nM)`, `Percent Control`) %>%
  count(n)
```


```{r}
per_conc <- single_dose %>%
  select(hmsl_id, `DiscoveRx Gene Symbol`, `Compound Concentration (nM)`, `Percent Control`) %>%
  pivot_wider(
    id_cols = c(hmsl_id, `DiscoveRx Gene Symbol`),
    names_from = `Compound Concentration (nM)`,
    values_from = `Percent Control`,
    values_fn = mean
  )

p <- per_conc %>%
  drop_na(`100`, `1000`) %>%
  ggplot(aes(`100`, `1000`)) +
  geom_point()
```

```{r}
library(rasterly)
p <- per_conc %>%
  drop_na(`100`, `1000`) %>%
  ggRasterly(
    mapping = aes(x = `100`, y = `1000`), color = rev(viridis_map),
    shape = 16
  ) +
  theme_minimal() +
  geom_segment(aes(x = 0, y = 0, xend = 100, yend = 100), size = 0.2) +
  labs(
    color = "Density"
  )
ggsave(
  here("percent_control_100_vs_1000.pdf"),
  p, width = 4, height = 3
)
```

```{r}
library(rasterly)
p <- per_conc %>%
  drop_na(`100`, `10000`) %>%
  mutate(
    across(where(is.numeric), ~log10(.x + 0.01))
  ) %>%
  ggRasterly(
    mapping = aes(x = `100`, y = `10000`), color = rev(viridis_map),
    shape = 16
  ) +
  theme_minimal() +
  labs(
    color = "Density"
  )
ggsave(
  here("percent_control_100_vs_10000_log.pdf"),
  p, width = 4, height = 3
)
```

```{r}
p <- per_conc %>%
  drop_na(`100`, `10000`) %>%
  plotly::plot_ly(x = ~`100`, y = ~`10000`) %>%®
  add_rasterly_heatmap(scaling = "log")
```


Number of targets per drug under threshold

```{r}
binding_stats <- single_dose %>%
  group_by(`Compound Concentration (nM)`, `hmsl_id`) %>%
  summarize(
    n_total = n(),
    n_decided = sum(tas %in% c(2, 10), na.rm = TRUE),
    n_binding = sum(tas == 2, na.rm = TRUE),
    n_nonbinding = sum(tas == 10, na.rm = TRUE),
    n_below_50 = sum(`Percent Control` < 50),
    .groups = "drop"
  ) %>%
  mutate(
    frac_binding = n_binding / n_decided,
    frac_nonbinding = n_nonbinding / n_decided,
    frac_below_50 = n_below_50 / n_total
  )
```

```{r}
p <- binding_stats %>%
  drop_na(n_binding) %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  ggplot(aes(n_binding, color = as.ordered(`Compound Concentration (nM)`))) +
    geom_freqpoly() +
    labs(color = "Concentration")

p <- binding_stats %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  ggplot(aes(n_below_50, color = as.ordered(`Compound Concentration (nM)`))) +
    geom_freqpoly() +
    labs(color = "Concentration", x = "N inhibition below 50%")
ggsave("n_below_50_histogram.pdf", p, width = 5, height = 3)
```




```{r}
p <- binding_stats %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  arrange(desc(n_binding)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  mutate(
    rank_n_binding = seq_len(n())
  ) %>%
  ungroup() %>%
  ggplot(
    aes(
      rank_n_binding, n_binding,
      color = as.ordered(`Compound Concentration (nM)`)
    )
  ) +
    geom_step() +
    labs(
      title = "N of bound targets (TAS = 2) per drug",
      color = "Concentration"
    )

p <- binding_stats %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  arrange(desc(n_below_50)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  mutate(
    rank_n_below_50 = seq_len(n())
  ) %>%
  ungroup() %>%
  ggplot(aes(rank_n_below_50, n_below_50, color = as.ordered(`Compound Concentration (nM)`))) +
    geom_step() +
    labs(
      title = "N of targets with >50% inhibition per drug",
      color = "Concentration"
    )

p <- binding_stats %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  arrange(desc(frac_binding)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  mutate(
    rank_frac_binding = seq_len(n())
  ) %>%
  ungroup() %>%
  ggplot(
    aes(
      rank_frac_binding, frac_binding,
      color = as.ordered(`Compound Concentration (nM)`)
    )
  ) +
    geom_step(alpha = 0.8) +
    labs(
      title = "Fraction of targets that are bound by drug",
      color = "Concentration"
    )
ggsave("rank_frac_binding.pdf", p, width = 5, height = 3)

p <- binding_stats %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  arrange(desc(frac_below_50)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  mutate(
    rank_frac_below_50 = seq_len(n())
  ) %>%
  ungroup() %>%
  ggplot(aes(rank_frac_below_50, frac_below_50, color = as.ordered(`Compound Concentration (nM)`))) +
    geom_step(alpha = 0.8) +
    labs(
      title = "Fraction of targets with >50% inhibition by drug",
      color = "Concentration"
    )
ggsave("rank_frac_below_50.pdf", p, width = 5, height = 3)
```

### Heatmaps

```{r}
percent_remaining_mats <- single_dose %>%
  inner_join(
    kinase_info %>%
      select(`DiscoveRx Gene Symbol`, `Kinase Form`)
  ) %>%
  # filter(`Kinase Form` == "Wild Type") %>%
  group_nest(`Compound Concentration (nM)`) %>%
  crossing(trans = c("log", "lin")) %>%
  mutate(
    mat = map2(
      data, trans,
      function(data, trans) {
        trans_fun <- if (trans == "log")
          function(x) log10(x + 0.01)
        else
          identity
        data %>%
          mutate(across(`Percent Control`, trans_fun)) %>%
          select(hmsl_id, `DiscoveRx Gene Symbol`, `Percent Control`) %>%
          pivot_wider(values_from = `Percent Control`, names_from = hmsl_id, values_fn = mean) %>%
          column_to_rownames("DiscoveRx Gene Symbol")
      }
    )
  ) %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000))

library(pheatmap)
library(seriation)
viridis_map <- viridis::viridis(100)
percent_remaining_heatmaps <- percent_remaining_mats %>%
  mutate(
    heatmap = map(
      mat,
      function(mat) {
        set.seed(42)
        mat <- t(mat)
        dr <- dist(mat, method = "euclidean")
        dc <- dist(t(mat), method = "euclidean")
        cr <- hclust(dr, method = "average") %>%
          reorder(dr, method = "olo")
        cc <- hclust(dc, method = "average") %>%
          reorder(dc, method = "olo")
        pheatmap(
          mat,
          show_rownames = FALSE, show_colnames = FALSE,
          color = rev(viridis_map),
          cluster_rows = cr, cluster_cols = cc,
          treeheight_row = 20, treeheight_col = 20
        )
      }
    )
  )

dir.create("heatmaps", showWarnings = FALSE)
pwalk(
  percent_remaining_heatmaps,
  function(heatmap, `Compound Concentration (nM)`, trans, ...) {
    ggsave(
      paste0("heatmaps/heatmap_all_", `Compound Concentration (nM)`, "_", trans, ".pdf"),
      heatmap, width = 5, height = 3
    )
  }
)

```


```{r}
p <- single_dose %>%
  filter(hmsl_id == "HMSL10139", `DiscoveRx Gene Symbol` %in% c("TYK2(JH1domain-catalytic)", "JAK3(JH1domain-catalytic)", "NEK10", "PRKCE")) %>%
  ggplot(aes(`Compound Concentration (nM)`, `Percent Control`, color = `Entrez Gene Symbol`)) +
    # geom_line() +
    # geom_point(alpha = 0.8) +
    geom_beeswarm(alpha = 0.8) +
    scale_x_log10() +
    theme_minimal() +
    geom_line() +
    labs(title = "JAK inhibitor AZD1480")

ggsave(
  "dose_respons_scatter_AZD1480.pdf",
  p, width = 4, height = 2.5
)

p <- single_dose %>%
  filter(hmsl_id == "HMSL10139", `DiscoveRx Gene Symbol` %in% c("TYK2(JH1domain-catalytic)", "JAK3(JH1domain-catalytic)", "NEK10", "PRKCE")) %>%
  ggplot(aes(`Compound Concentration (nM)`, log10(`Percent Control` + 0.0005), color = `Entrez Gene Symbol`)) +
    # geom_line() +
    # geom_point(alpha = 0.8) +
    geom_beeswarm(alpha = 0.8) +
    scale_x_log10() +
    theme_minimal() +
    geom_line() +
    labs(title = "JAK inhibitor AZD1480", y = "log10(Percent Control)")

ggsave(
  "dose_response_scatter_log_AZD1480.pdf",
  p, width = 4, height = 2.5
)
```

```{r}
single_dose_trans <- single_dose %>%
  left_join(
    qpcr_misses %>%
      transmute(
        hmsl_id = `Compound Name`,
        `DiscoveRx Gene Symbol` = `Ambit Gene Symbol`,
        `Compound Conc`,
        qpcr_miss = TRUE
      ),
    by = c("hmsl_id", "DiscoveRx Gene Symbol", "Compound Concentration (nM)" = "Compound Conc")
  ) %>%
  mutate(
    log_inhibition = log10(`Percent Control` + 0.01),
    qpcr_miss = replace_na(qpcr_miss, FALSE)
  ) %>%
  as_tibble()

single_dose_trans %>%
  count(qpcr_miss)

largest_inconsistency <- single_dose %>%
  mutate(across(`Percent Control`, ~log10(.x + 0.01))) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    `Compound Concentration (nM)`
  ) %>%
  summarize(across(`Percent Control`, mean), .groups = "drop") %>%
  arrange(`Compound Concentration (nM)`) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    data = list(cur_data()),
    drops = list(`Percent Control`[-1] - `Percent Control`[-n()]),
    .groups = "drop"
  ) %>%
  mutate(
    max_inhib = map_dbl(data, ~min(.x$`Percent Control`)),
    largest_increase_idx = map_int(drops, ~which.max(magrittr::inset(.x, .x < 0, 0))),
    largest_increase_conc = map2_chr(largest_increase_idx, data, ~paste(.y$`Compound Concentration (nM)`[c(.x, .x + 1)], collapse = "-")),
    largest_increase = map_dbl(drops, ~max(magrittr::inset(.x, .x < 0, 0))),
    drops_auc = map_dbl(drops, sum),
    # largest_increase_norm = map2_dbl(largest_increase, data, ~.x - mean(.y$`Percent Control`))
    largest_increase_norm = largest_increase - drops_auc
  ) %>%
  as_tibble()

between_doses <- single_dose_trans %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    `Compound Concentration (nM)`
  ) %>%
  summarize(across(log_inhibition, mean), .groups = "drop") %>%
  arrange(`Compound Concentration (nM)`) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    data = list(cur_data()),
    drops = list(log_inhibition[-1] - log_inhibition[-n()]),
    pc_extended = list(c(log10(100 + 0.01), log_inhibition, log10(0 + 0.01))),
    .groups = "drop"
  ) %>%
  mutate(
    max_inhib = map_dbl(data, ~min(.x$log_inhibition)),
    largest_increase_idx = map_int(drops, ~which.max(magrittr::inset(.x, .x < 0, 0))),
    largest_increase_inhib = map2_dbl(drops, largest_increase_idx, magrittr::extract),
    largest_increase_conc = map2_chr(largest_increase_idx, data, ~paste(.y$`Compound Concentration (nM)`[c(.x, .x + 1)], collapse = "-")),
    largest_increase = map_dbl(drops, ~max(magrittr::inset(.x, .x < 0, 0))),
    drops_auc = map_dbl(drops, sum),
    # largest_increase_norm = map2_dbl(largest_increase, data, ~.x - mean(.y$`Percent Control`))
    largest_increase_norm = largest_increase - drops_auc
  ) %>%
  mutate(
    # data = pmap(
    #   list(pc_extended, data),
    #   function(pc_extended, data) {
    #     data %>%
    #       mutate(
    #         means = (pc_extended[-c(1, 2)] + head(pc_extended, -2)) * 0.5,
    #         mean_diff = log_inhibition - means
    #       )
    #   }
    # )
    means = map(pc_extended, ~(.x[-c(1, 2)] + head(.x, -2)) * 0.5),
    mean_diff = map2(means, data, ~.y$log_inhibition - .x),
    # largest_increase_idx = map_int(drops, ~which.max(magrittr::inset(.x, .x < 0, 0)))
  ) %>%
  mutate(
    possible_sus = map(largest_increase_idx, ~c(0, 1) + .x),
    sus_index = map2(mean_diff, possible_sus, ~.y[which.max(abs(.x)[.y])]) %>%
      unlist(),
    sus_mean_diff = map2_dbl(mean_diff, sus_index, ~.x[.y]),
    sus_conc = map2_dbl(sus_index, data, ~.y$`Compound Concentration (nM)`[.x])
  ) %>%
  mutate(
    is_bad = largest_increase > 0.5
  )

flagged_data <- between_doses %>%
  select(
    lspci_id, hmsl_id,
    `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    data, sus_conc, is_bad,
  ) %>%
  unnest(data) %>%
  mutate(flagged = `Compound Concentration (nM)` == sus_conc & is_bad) %>%
  select(-sus_conc) %>%
  rename(contains_flagged = is_bad) %>%
  left_join(
    compound_names
  )

write_csv(flagged_data, "okl_kinomescan_flagged.csv.gz")
```


```{r}
p <- between_doses

```


```{r}
library(ggrepel)

p <- flagged_data %>%
  group_by(
    `Compound Concentration (nM)`
  ) %>%
  summarize(
    frac_below_50 = sum(log_inhibition < log10(0.501)) / n(),
    frac_flagged = sum(flagged) / n(),
    .groups = "drop"
  ) %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  ggplot(
    aes(frac_below_50, frac_flagged)
  ) +
  geom_point() +
  geom_text_repel(
    aes(label = `Compound Concentration (nM)`),
    min.segment.length = unit(0, "lines"),
    max.overlaps = 20, max.iter = 50000, max.time = 2.5
  ) +
  labs(
    x = "Fraction of measurements <50% remaining",
    y = "Fraction of flagged measurements"
  ) +
  theme_light()

ggsave(
  "fraction_below_50_vs_fraction_flagged_concentrations.pdf",
  p, width = 5, height = 5
)

flagged_data %>%
  summarize(
    n = sum(flagged),
    frac = n / n()
  )

flagged_data %>%
  group_by(`Compound Concentration (nM)`) %>%
  summarize(
    n = sum(flagged),
    frac = n / n(),
    .groups = "drop"
  )

n_flagged <- flagged_data %>%
  group_by(lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`) %>%
  summarize(
    any_flagged = any(flagged),
    any_active = log_inhibition < log10(50),
    .groups = "drop"
  )

n_flagged %>%
  summarize(
    n = sum(any_flagged),
    frac = n / n(),
    .groups = "drop"
  )


n_flagged %>%
  group_by(any_active) %>%
  summarize(
    n = sum(any_flagged),
    frac = n / n(),
    .groups = "drop"
  )

library(ggalluvial)

n_flagged %>%
  group_by(any_flagged, any_active) %>%
  summarize(Freq = n(), .groups = "drop") %>%
  mutate(across(c(-Freq), as.factor)) %>%
  ggplot(y = Freq, axis1 = any_flagged, axis2 = any_active) +
  geom_alluvium() +
  geom_stratum() +
  geom_label(stat = "stratum")

library(alluvial)

n_flagged %>%
  group_by(any_flagged, any_active) %>%
  summarize(Freq = n(), .groups = "drop") %>%
  mutate(across(c(-Freq), as.factor)) %>% {
    alluvial(
      select(., -Freq), freq=.$Freq
    )
  }


```


```{r}
library(ggrepel)

p <- flagged_data %>%
  group_by(
    lspci_id, hmsl_id, `Compound Concentration (nM)`
  ) %>%
  summarize(
    frac_below_50 = sum(log_inhibition < log10(0.501)) / n(),
    frac_flagged = sum(flagged) / n(),
    .groups = "drop"
  ) %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  arrange(desc(frac_flagged)) %>%
  mutate(top_10_flagged = seq_len(n()) %in% 1:10) %>%
  ungroup() %>%
  ggplot(
    aes(frac_below_50, frac_flagged)
  ) +
  geom_point() +
  facet_wrap(~`Compound Concentration (nM)`, scales = "free") +
  geom_text_repel(
    aes(label = paste0(name, "nM")),
    data = ~.x %>%
      filter(top_10_flagged) %>%
      left_join(compound_names),
    min.segment.length = unit(0, "lines"),
    max.overlaps = 20, max.iter = 50000, max.time = 2.5
  ) +
  labs(
    x = "Fraction of measurements <50% remaining",
    y = "Fraction of flagged measurements"
  ) +
  theme_light()


ggsave(
  "fraction_below_50_vs_fraction_flagged.pdf",
  p, width = 10, height = 8
)

p <- flagged_data %>%
  group_by(
    `Compound Concentration (nM)`, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    frac_below_50 = sum(log_inhibition < log10(0.501)) / n(),
    frac_flagged = sum(flagged) / n(),
    .groups = "drop"
  ) %>%
  filter(`Compound Concentration (nM)` %in% c(12.5, 100, 1000, 10000)) %>%
  group_by(`Compound Concentration (nM)`) %>%
  arrange(desc(frac_flagged)) %>%
  mutate(top_10_flagged = seq_len(n()) %in% 1:10) %>%
  ungroup() %>%
  ggplot(
    aes(frac_below_50, frac_flagged)
  ) +
  geom_point() +
  facet_wrap(~`Compound Concentration (nM)`, scales = "free") +
  geom_text_repel(
    aes(label = `DiscoveRx Gene Symbol`),
    data = ~.x %>%
      filter(top_10_flagged),
    min.segment.length = unit(0, "lines"),
    max.overlaps = 20, max.iter = 50000, max.time = 2.5
  ) +
  labs(
    x = "Fraction of measurements <50% remaining",
    y = "Fraction of flagged measurements"
  ) +
  theme_light()


ggsave(
  "fraction_below_50_vs_fraction_flagged_targets.pdf",
  p, width = 10, height = 8
)
```


```{r}
p <- between_doses %>%
  ggplot(
    aes(sus_mean_diff, largest_increase)
  ) +
    geom_point()

p <- between_doses %>%
  mutate(
    is_bad = largest_increase > 0.8
  ) %>%
  ggplot(
    aes(factor(sus_conc))
  ) +
    geom_bar() +
    facet_wrap(~is_bad)

n_conc_df <- between_doses %>%
  filter(is_bad) %>%
  unnest(data) %>%
  group_by(sus_conc) %>%
  summarize(n_dose = n(), .groups = "drop")

sus_conc_frac <- between_doses %>%
  filter(is_bad) %>%
  group_by(sus_conc) %>%
  summarize(
    n_bad = n(), .groups = "drop"
  ) %>%
  left_join(
    n_conc_df
  ) %>%
  mutate(frac_bad = n_bad / n_dose)

p <- sus_conc_frac %>%
  ggplot(
    aes(factor(sus_conc), frac_bad)
  ) +
    geom_col()

p <- between_doses %>%
  filter(is_bad) %>%
  ggplot(
    aes(factor(sus_conc))
  ) +
    geom_bar()

random_bad <- between_doses %>%
  filter(is_bad) %>%
  sample_n(10) %>%
  left_join(
    compound_dictionary %>%
      select(hmsl_id, pref_name)
  ) %>%
  mutate(
    measurement_name = paste(pref_name, "-", `DiscoveRx Gene Symbol`)
  )


p <- random_bad %>%
  mutate(
    data = map2(data, means, ~mutate(.x, means = .y))
  ) %>%
  select(-means) %>%
  unnest(data) %>%
  pivot_longer(c(log_inhibition, means)) %>%
  ggplot(aes(`Compound Concentration (nM)`, value, color = name, linetype = name)) +
    scale_color_manual(values = c("log_inhibition" = "black", "means" = "gray10")) +
    scale_linetype_manual(values = c("log_inhibition" = "solid", "means" = "dotted")) +
    geom_line() +
    facet_wrap(~measurement_name) +
    scale_x_log10() +
    geom_segment(
      aes(sus_conc, xend = sus_conc), inherit.aes = FALSE,
      y = -2, yend = -1, color = "red", data = random_bad
    )
ggsave(
  "random_bad_2.pdf", p, width = 8, height = 6
)
```

### asdfasdf

```{r}
p <- largest_inconsistency %>%
  ggplot(aes(largest_increase)) +
    geom_histogram() +
    geom_vline(xintercept = 0.5, color = "red")

ggsave(
  "largest_increase_hist.pdf",
  p, width = 4, height = 2
)

p <- largest_inconsistency %>%
  ggplot(aes(largest_increase, largest_increase_norm)) +
    geom_point()

p <- largest_inconsistency %>%
  ggplot(aes(largest_decrease, largest_increase)) +
    geom_point()

p <- largest_inconsistency %>%
  ggplot(aes(drops_auc, largest_increase)) +
    geom_point()

p <- largest_inconsistency %>%
  ggplot(aes(max_inhib, largest_increase)) +
    geom_point()

p <- largest_inconsistency %>%
  ggplot(aes(largest_increase_conc, largest_increase)) +
    geom_quasirandom(groupOnX = TRUE)
```


```{r}
rois <- largest_inconsistency %>%
  mutate(
    roi = case_when(
      largest_increase > 3 & largest_decrease < -3 ~ "top_left",
      largest_increase > 3 & largest_decrease > -1 ~ "top_right",
      TRUE ~ "none"
    )
  ) %>%
  filter(roi != "none") %>%
  select(where(negate(is.list)))

```

```{r}

```


```{r}
n_inconsistent_per_target <- largest_inconsistency %>%
  mutate(largest_increase_bad = largest_increase > 0.5) %>%
  group_by(`DiscoveRx Gene Symbol`, `Entrez Gene Symbol`) %>%
  summarize(
    n_bad = sum(largest_increase_bad),
    n_bad_norm = sum(largest_increase_bad) / sum(max_inhib < 0.5),
    # Normalize by number of active targets
    frac_bad = n_bad / n(),
    # Only take into account bad
    mean_largest_increase = mean(largest_increase),
    # badness_score = sum(largest_increase) + sum(max_inhib),
    .groups = "drop"
  ) %>%
  arrange(desc(n_bad_norm))

n_inconsistent_per_compound <- largest_inconsistency %>%
  mutate(largest_increase_bad = largest_increase > 0.5) %>%
  group_by(`lspci_id`, `hmsl_id`) %>%
  summarize(
    n_bad = sum(largest_increase_bad),
    frac_bad = n_bad / n(),
    mean_largest_increase = mean(largest_increase),
    # badness_score = sum(largest_increase) + sum(max_inhib),
    .groups = "drop"
  ) %>%
  arrange(desc(frac_bad)) %>%
  left_join(
    compound_dictionary %>%
      select(hmsl_id, pref_name)
  )

```




```{r}
p <- n_inconsistent_per_target %>%
  ggplot(aes(frac_bad)) +
    geom_histogram()

ggsave(
  "frac_bad_per_target_hist.pdf",
  p, width = 4, height = 2
)

p <- n_inconsistent_per_compound %>%
  ggplot(aes(frac_bad)) +
    geom_histogram()

ggsave(
  "frac_bad_per_compound_hist.pdf",
  p, width = 4, height = 2
)

```

```{r}
p <- single_dose %>%
  filter(`DiscoveRx Gene Symbol` == "ACVR1B") %>%
  # head(n = 10) %>%
  ggplot(aes(as.ordered(`Compound Concentration (nM)`), `Percent Control`, group = hmsl_id)) +
  geom_line() +
  geom_point() +
  facet_wrap(~hmsl_id) +
  labs(x = "Concentration (nM)")

ggsave(
  "asdf.png",
  p, width = 10, height = 7
)
```

```{r}
plot_beeswarm_single_drug <- function(name) {
  library(ggbeeswarm)
  lspci_id <- if (is.numeric(name))
    name
  else if (str_starts(name, "HMSL"))
    compound_mapping[external_id == name][["lspci_id"]][1]
  else
    compound_dictionary[pref_name == name][["lspci_id"]][1, 1]
  single_dose %>%
    filter(lspci_id == .env$lspci_id) %>%
    ggplot(aes(as.ordered(`Compound Concentration (nM)`), `Percent Control`)) +
      geom_quasirandom()
}

plot_heatmap_single_drug <- function(name) {
  library(ggbeeswarm)
  lspci_id <- if (is.numeric(name))
    name
  else if (str_starts(name, "HMSL"))
    compound_mapping[external_id == name][["lspci_id"]][1]
  else
    compound_dictionary[pref_name == name][["lspci_id"]][1, 1]
  d <- single_dose %>%
    filter(lspci_id == .env$lspci_id) %>%
    mutate(across(`Compound Concentration (nM)`, . %>% as.factor() %>% fct_inseq())) %>%
    select(`DiscoveRx Gene Symbol`, `Compound Concentration (nM)`, `Percent Control`) %>%
    pivot_wider(names_from = `DiscoveRx Gene Symbol`, values_from = `Percent Control`) %>%
    column_to_rownames("Compound Concentration (nM)")
  ComplexHeatmap::Heatmap(
    as.matrix(d),
    show_column_names = FALSE,
    cluster_rows = FALSE,
    row_order = order(as.double(rownames(d))),
    col = rev(viridis_map)
  )
  # pheatmap(
  #   d, show_rownames = TRUE, show_colnames = FALSE,
  #   cluster_rows = FALSE,
  #   color = rev(viridis_map)
  # )
    # ggplot(
    #   aes(
    #     `DiscoveRx Gene Symbol`,
    #     as.ordered(`Compound Concentration (nM)`),
    #     fill = `Percent Control`
    #   )
    # ) +
    # geom_tile() +
    # scale_fill_viridis_c(direction = -1)
}

plot_single_drug <- function(drug, target) {
  library(ggbeeswarm)
  lspci_id <- if (is.numeric(drug))
    drug
  else if (str_starts(drug, "HMSL"))
    compound_mapping[external_id == drug][["lspci_id"]][1]
  else
    compound_dictionary[pref_name == drug][["lspci_id"]][1, 1]
  df <- single_dose %>%
    filter(lspci_id == .env$lspci_id, str_detect(`DiscoveRx Gene Symbol`, target))
  p <- df %>%
    ggplot(aes(as.ordered(`Compound Concentration (nM)`), `Percent Control`)) +
      geom_quasirandom(groupOnX = TRUE)
  if (length(unique(df$`DiscoveRx Gene Symbol`)) > 1)
    p <- p +
      facet_wrap(~`DiscoveRx Gene Symbol`)
  p
}

plot_single_drug("HMSL10004", "TYK2")

p <- plot_heatmap_single_drug("HMSL10139")
withr::with_pdf(
  "AZD1480_dose_response_hm.pdf",
  ComplexHeatmap::draw(plot_heatmap_single_drug("HMSL10139")), width = 6, height = 2
)
ggsave(
  "AZD1480_dose_response_hm.pdf",
  p, width = 6, height = 2.5
)

```


```{r binary_flagging}
binary_between_doses <- single_dose_trans %>%
    group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    `Compound Concentration (nM)`
  ) %>%
  summarize(
    across(
      c(`Percent Control`, log_inhibition),
      ~if (!all(qpcr_miss))
        mean(.x[!qpcr_miss])
      else
        mean(.x)
    ),
    qpcr_miss = all(qpcr_miss),
    .groups = "drop"
  ) %>%
  arrange(`Compound Concentration (nM)`) %>%
  mutate(
    inhib_hit = `Percent Control` <= 35 & !qpcr_miss
  ) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    data = list(cur_data()),
    # inhib_concordant = {
    #   !any((inhib_hit[-1] - head(inhib_hit, -1)) < 0)
    # },
    inhib_concordant = if (any(inhib_hit)) {
      cg <- cur_group()
      # if (cg[["Entrez Gene Symbol"]] == "MKNK1" && cg[["lspci_id"]] == 17778) browser()
      inhib_idx <- which(inhib_hit)[1]
      if (inhib_idx == length(inhib_hit))
        TRUE
      else {
        after <- tail(`Percent Control`, -inhib_idx)
        x <- !any((after > 35) & (after > (2 * `Percent Control`[inhib_idx])))
        # if (x) browser()
        x
      }
    } else {
        TRUE
    },
    .groups = "drop"
  )


n_flagged_binary <- binary_between_doses %>%
  mutate(
    any_active = map_lgl(
      data, ~any(.x$`Percent Control` <= 35)
    )
  )

n_flagged_binary %>%
  summarize(
    n = sum(!inhib_concordant),
    frac = n / n(),
    .groups = "drop"
  )


n_flagged_binary %>%
  group_by(any_active) %>%
  summarize(
    n = sum(!inhib_concordant),
    frac = n / n(),
    .groups = "drop"
  )

binary_between_doses <- single_dose_trans %>%
  filter(qpcr_miss == FALSE) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    `Compound Concentration (nM)`
  ) %>%
  summarize(
    across(c(`Percent Control`, log_inhibition), mean),
    .groups = "drop"
  ) %>%
  arrange(`Compound Concentration (nM)`) %>%
  mutate(
    inhib_hit = `Percent Control` <= 35
  ) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    data = list(cur_data()),
    inhib_concordant = !any((inhib_hit[-1] - head(inhib_hit, -1)) < 0),
    .groups = "drop"
  ) %>%
  as_tibble()


n_flagged_binary <- binary_between_doses %>%
  mutate(
    any_active = map_lgl(
      data, ~any(.x$`Percent Control` <= 35)
    )
  )

n_flagged_binary %>%
  summarize(
    n = sum(!inhib_concordant),
    frac = n / n(),
    .groups = "drop"
  )


n_flagged_binary %>%
  group_by(any_active) %>%
  summarize(
    n = sum(!inhib_concordant),
    frac = n / n(),
    .groups = "drop"
  )
```

```{r}
single_dose_trans_agg <- single_dose_trans %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`,
    `Compound Concentration (nM)`
  ) %>%
  summarize(
    across(
      c(`Percent Control`, log_inhibition),
      ~if (!all(qpcr_miss))
        mean(.x[!qpcr_miss])
      else
        mean(.x)
    ),
    qpcr_miss = all(qpcr_miss),
    .groups = "drop"
  ) %>%
  arrange(`Compound Concentration (nM)`)

single_dose_hits <- single_dose_trans %>%
  mutate(
    inhib_hit = `Percent Control` <= 35 & !qpcr_miss,
    log_conc = log10(`Compound Concentration (nM)`)
  ) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  summarize(
    data = list(cur_data()),
    lin_mod = list(
      lm(`Percent Control` ~ log_conc, data = cur_data())
    ),
    # inhib_concordant = {
    #   !any((inhib_hit[-1] - head(inhib_hit, -1)) < 0)
    # },
    inhib_concordant = if (any(inhib_hit)) {
      cg <- cur_group()
      # if (cg[["Entrez Gene Symbol"]] == "MKNK1" && cg[["lspci_id"]] == 17778) browser()
      inhib_idx <- which(inhib_hit)[1]
      if (inhib_idx == length(inhib_hit))
        TRUE
      else {
        after <- tail(`Percent Control`, -inhib_idx)
        x <- !any((after > 35) & (after > (2 * `Percent Control`[inhib_idx])))
        # if (x) browser()
        x
      }
    } else {
        TRUE
    },
    .groups = "drop"
  )

library(broom)
single_dose_classification_res <- single_dose_hits %>%
  mutate(
    lin_mod_res = map(lin_mod, tidy)
  )

single_dose_classification_res2 <- single_dose_classification_res %>%
  unnest(lin_mod_res) %>%
  filter(term == "log_conc")

single_dose_classification <- single_dose_classification_res2 %>%
  rowwise() %>%
  mutate(
    classification = {
      if (!inhib_concordant) {
        "discordant"
      } else if (all(!data$inhib_hit)) {
        "non-binding"
      } else if (inhib_concordant && sum(data$inhib_hit) >= 2) {
        "binding"
      } else if (!is.na(estimate) && !is.na(p.value) && estimate < 0 && p.value < 0.1) {
        "weakly-binding"
      } else {
        "undetermined"
      }
    } %>%
      factor(
        levels = c("binding", "weakly-binding", "non-binding", "undetermined", "discordant"),
        ordered = TRUE
      )
  ) %>%
  ungroup() %>%
  power_left_join(
    compound_names,
    by = "lspci_id",
    check = check_specs(
      duplicate_keys_right = "abort",
      unmatched_keys_left = "abort",
      unmatched_keys_right = "ignore"
    )
  ) %>%
  select(
    lspci_id, name, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`, classification, everything()
  )

write_csv(
  single_dose_classification %>%
    select(where(negate(is.list))),
  "classification/okl_eurofins_classification.csv"
)
single_dose_classification <- read_csv("classification/okl_eurofins_classification.csv")

single_dose_classification %>%
  group_by(classification) %>%
  summarize(
    n = n(),
    frac_total = n() / nrow(.),
    frac_binding = n() / sum(map_lgl(.$data, ~any(.x$inhib_hit))),
    .groups = "drop"
  )

library(powerjoin)
p <- single_dose_classification %>%
  count(lspci_id, name, classification) %>%
  complete(nesting(lspci_id, name), classification, fill = list(n = 0)) %>%
  group_by(lspci_id, name) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup() %>%
  mutate(
    name = factor(
      name,
      levels = filter(., classification == "binding") %>%
        arrange(frac) %>%
        pull(name)
    )
  ) %>%
  arrange(desc(name)) %>%
  mutate(split_var = floor(seq(from = 0, to = 2.99999, length.out = n()))) %>%
  ggplot(aes(frac, name, color = classification)) +
    geom_point() +
    scale_color_manual(
      values = c(
        "binding" = "firebrick1",
        "weakly-binding" = "darkorange",
        "non-binding" = "black",
        "undetermined" = "gray",
        "discordant" = "blue"
      )
    ) +
    facet_wrap(~split_var, scales = "free_y", nrow = 1) +
    theme(strip.text = element_blank()) +
    labs(x = "Fraction of dose-response curves", y = "Compound")

dir.create("classification")
ggsave(
  "classification/lm_classification_waterfall.pdf", p, width = 18, height = 10
)


library(powerjoin)
p <- single_dose_classification %>%
  count(`DiscoveRx Gene Symbol`, classification) %>%
  complete(`DiscoveRx Gene Symbol`, classification, fill = list(n = 0)) %>%
  group_by(`DiscoveRx Gene Symbol`) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup() %>%
  mutate(
    `DiscoveRx Gene Symbol` = factor(
      `DiscoveRx Gene Symbol`,
      levels = filter(., classification == "binding") %>%
        arrange(frac) %>%
        pull(`DiscoveRx Gene Symbol`)
    )
  ) %>%
  arrange(desc(`DiscoveRx Gene Symbol`)) %>%
  mutate(split_var = floor(seq(from = 0, to = 2.99999, length.out = n()))) %>%
  ggplot(aes(frac, `DiscoveRx Gene Symbol`, color = classification)) +
    geom_point() +
    scale_color_manual(
      values = c(
        "binding" = "firebrick1",
        "weakly-binding" = "darkorange",
        "non-binding" = "black",
        "undetermined" = "gray",
        "discordant" = "blue"
      )
    ) +
    facet_wrap(~split_var, scales = "free_y", nrow = 1) +
    theme(strip.text = element_blank()) +
    labs(x = "Fraction of dose-response curves", y = "Kinase")

ggsave(
  "classification/lm_classification_waterfall_kinases.pdf", p, width = 18, height = 14
)


library(ggbeeswarm)
p <- single_dose_classification %>%
  count(lspci_id, name, classification) %>%
  complete(nesting(lspci_id, name), classification, fill = list(n = 0)) %>%
  group_by(lspci_id, name) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup() %>%
  mutate(
    name = factor(
      name,
      levels = filter(., classification == "binding") %>%
        arrange(frac) %>%
        pull(name)
    )
  ) %>%
  ggplot(aes(classification, frac)) +
    geom_quasirandom()

ggsave(
  "classification/hist_classes.pdf", p, width = 8, height = 6
)

library(egg)
set.seed(42)
p <- single_dose_classification %>%
  group_by(classification) %>%
  slice_sample(n = 10) %>%
  ungroup() %>%
  mutate(binding_name = paste(name, `Entrez Gene Symbol`, sep = " - ")) %>%
  unnest(data) %>%
  ggplot(aes(`Compound Concentration (nM)`, `Percent Control`)) +
    geom_rect(
      aes(fill = classification, xmin = 10, xmax = 10000,
      ymin = 0, ymax = 100),
      alpha = 0.5,
      data = ~.x %>%
        distinct(binding_name, classification),
      inherit.aes = FALSE
    ) +
    geom_point() +
    geom_line() +
    scale_x_log10() +
    geom_hline(yintercept = 35) +
    facet_wrap(~classification + binding_name) +
    # geom_custom(
    #   data = ~.x %>%
    #     distinct(binding_name, classification),
    #   mapping = aes(fill = classification),
    #   grob_fun = function(x) rectGrob(gp=gpar(fill=fill,col=NA, alpha=0.5)),
    #   inherit.aes = TRUE
    # ) +
    geom_text(
      aes(label = paste(round(estimate, digits = 1), signif(p.value, digits = 2))),
      data = ~.x %>%
        distinct(classification, binding_name, estimate, p.value),
      x = 20, y = 20
    )
ggsave(
  "classification/class_examples.pdf", p, width = 14, height = 12
)

single_dose_classification %>%
  filter(
    name == "SILMITASERTIB",
    `Entrez Gene Symbol` == "MAP2K2"
  ) %>%
  View()

library(ggrepel)
p <- single_dose_classification %>%
  count(lspci_id, name, classification) %>%
  complete(nesting(lspci_id, name), classification, fill = list(n = 0)) %>%
  group_by(lspci_id, name) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup() %>%
  # mutate(
  #   name = factor(
  #     name,
  #     levels = filter(., classification == "binding") %>%
  #       arrange(frac) %>%
  #       pull(name)
  #   )
  # ) %>%
  select(lspci_id, name, classification, frac) %>%
  pivot_wider(names_from = classification, values_from = frac) %>%
  ggplot(aes(binding, discordant)) +
    geom_point() +
    geom_text_repel(
      aes(label = name),
      data = ~.x %>%
        mutate(name = if_else(discordant < 0.04, "", name)),
      min.segment.length = 0
    ) +
    labs(x = "Fraction of 'binding' dose-response curves", y = "Fraction of 'discordant' dose-response curves")

ggsave(
  "classification/discordant_vs_binding.pdf", p, width = 10, height = 10
)


p <- single_dose_classification %>%
  count(`DiscoveRx Gene Symbol`, classification) %>%
  complete(`DiscoveRx Gene Symbol`, classification, fill = list(n = 0)) %>%
  group_by(`DiscoveRx Gene Symbol`) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup() %>%
  # mutate(
  #   name = factor(
  #     name,
  #     levels = filter(., classification == "binding") %>%
  #       arrange(frac) %>%
  #       pull(name)
  #   )
  # ) %>%
  select(`DiscoveRx Gene Symbol`, classification, frac) %>%
  pivot_wider(names_from = classification, values_from = frac) %>%
  ggplot(aes(binding, discordant)) +
    geom_point() +
    geom_text_repel(
      aes(label = `DiscoveRx Gene Symbol`),
      data = ~.x %>%
        mutate(`DiscoveRx Gene Symbol` = if_else(discordant < 0.04, "", `DiscoveRx Gene Symbol`)),
      min.segment.length = 0
    ) +
    labs(x = "Fraction of 'binding' dose-response curves", y = "Fraction of 'discordant' dose-response curves")

ggsave(
  "classification/discordant_vs_binding_kinases.pdf", p, width = 10, height = 10
)

```

```{r pseudo_ic_50}
library(chemCal)
pseudo_ic50_raw <- single_dose_trans %>%
  filter(!qpcr_miss) %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`, `Compound Concentration (nM)`
  ) %>%
  summarize(`Percent Control` = mean(`Percent Control`), .groups = "drop") %>%
  group_by(
    lspci_id, hmsl_id, `DiscoveRx Gene Symbol`, `Entrez Gene Symbol`
  ) %>%
  arrange(`Compound Concentration (nM)`) %>%
  mutate(below_50 = `Percent Control` < 50, log_conc = log10(`Compound Concentration (nM)`)) %>%
  summarize(
    pseudo_ic50 = list(
      if (length(unique(below_50)) == 2 && !below_50[1]) {
        over_under_idx <- which(below_50)[1] + c(-1, 0)
        mdl_data <- cur_data()[over_under_idx, ]
        if (nrow(mdl_data) == 1)
          browser()
        mdl <- lm(`Percent Control` ~ log_conc, data = mdl_data)
        list(
          pseudo_ic50 = 10^(chemCal::inverse.predict(mdl, 50)$Prediction),
          relation = "="
        )
      } else if (all(below_50)) {
        list(
          pseudo_ic50 = min(`Compound Concentration (nM)`),
          relation= "<"
        )
      } else if (!any(below_50)) {
        list(
          pseudo_ic50 = max(`Compound Concentration (nM)`),
          relation= ">"
        )
      } else {
        list(
          pseudo_ic50 = NA_real_,
          relation = NA_character_
        )
      }
    ),
    .groups = "drop"
  )

pseudo_ic50 <- pseudo_ic50_raw %>%
  mutate(
    pseudo_ic50_relation = map_chr(pseudo_ic50, "relation"),
    pseudo_ic50 = map_dbl(pseudo_ic50, "pseudo_ic50")
  ) %>%
  power_left_join(
    compound_names,
    by = "lspci_id",
    check = check_specs(
      duplicate_keys_right = "abort",
      unmatched_keys_left = "abort",
      unmatched_keys_right = "ignore"
    )
  )

write_csv(
  pseudo_ic50,
  "classification/okl_eurofins_pseudo_ic50.csv"
)


```

