```{r}
library(tidyverse)
library(synExtra)
library(fst)
library(data.table)
library(powerjoin)
library(qs)
library(morgancpp)
library(ComplexHeatmap)
library(dendextend)

synapser::synLogin()

syn <- synDownloader(normalizePath("~/data"), .cache = TRUE)
```

```{r}
kinomescan_pseudo_kds <- syn("syn51080578") %>%
  read_csv() %>%
  filter(dataset == "original_repeat_replaced")

kinomescan_classes <- syn("syn51080579") %>%
  read_csv()

compound_props <- kinomescan_pseudo_kds %>%
  distinct(lspci_id, hmsl_id, name, library)

# kinomescan_classes <- syn("syn51080579") %>%
#   read_csv()

kinomescan_kinase_info <- syn("syn51286743") %>%
  read_csv()

fingerprints <- MorganFPS$new(syn("syn26262157"), from_file = TRUE)

compound_dictionary <- syn("syn26260332") %>%
  fst()
```



```{r}
okl_compound_info <- kinomescan_pseudo_kds %>%
  filter(library == "OKL") %>%
  distinct(
    lspci_id, hmsl_id, name, library
  )

okl_tanimoto_similarities <- fingerprints$tanimoto_subset(
  okl_compound_info$lspci_id, okl_compound_info$lspci_id
) %>%
  as_tibble() %>%
  power_inner_join(
    okl_compound_info %>%
      select(lspci_id, name_1 = name),
    by = c("id_1" = "lspci_id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  power_inner_join(
    okl_compound_info %>%
      select(lspci_id, name_2 = name),
    by = c("id_2" = "lspci_id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )

```


```{r}
library(ComplexHeatmap)
library(seriation)
library(impute)

cluster_fun_eucl <- function(mat, sample_in_col = TRUE) {
  if (!sample_in_col) {
    mat <- t(mat)
  }
  mat_imp <- impute.knn(
    mat, rng.seed = 42
  )[["data"]]
  if (!sample_in_col) {
    mat_imp <- t(mat_imp)
    mat <- t(mat)
  }
  # browser()
  dist_mat <- dist(mat_imp)
  # dist_mat <- as.dist(mat)
  clust <- hclust(dist_mat, method = "average")
  reorder(clust, dist_mat, method = "OLO")
}


createAnnotation <- function(df, colors = list(), which = "column", ...) {
  # Load necessary libraries
  color_maps <- list()

  # Iterate over each column in the dataframe
  for (col_name in names(df)) {
    # Check if the column is numeric
    if (is.numeric(df[[col_name]])) {
      # Create a color mapping function for numeric columns
      if (is.null(colors[[col_name]]))
        colors[[col_name]] <- c("white", "red")
      if (is.function(colors[[col_name]])) {
        col_fun <- colors[[col_name]]
      } else if (is.character(colors[[col_name]])) {
        n <- length(colors[[col_name]])
        if (n == 1) {
          col_fun <- circlize::colorRamp2(
            seq(from = min(df[[col_name]]), to = max(df[[col_name]]), length.out = 100),
            viridis(100, option = colors[[col_name]])
          )
        } else {
          col_fun <- circlize::colorRamp2(
            seq(from = min(df[[col_name]]), to = max(df[[col_name]]), length.out = n),
            colors[[col_name]]
          )
        }
      } else
        stop("Dont know how to handle colors for column ", col_name)
      color_maps[[col_name]] <- col_fun
    } else {
      if (is.character(colors[[col_name]])) {
        color_maps[[col_name]] <- colors[[col_name]]
        next
      }
      col_fun <- colors[[col_name]] %||% rainbow
      # Create a named vector of colors for categorical columns
      values <- df[[col_name]]
      unique_values <- if (is.factor(values)) levels(values) else unique(df[[col_name]])
      named_colors <- setNames(col_fun(length(unique_values)), unique_values)
      color_maps[[col_name]] <- named_colors
    }
  }

  # Combine all annotations
  combined_annotations <- HeatmapAnnotation(df = df, col = color_maps, which = which, ...)

  return(combined_annotations)
}


```


```{r}
kinomescan_pseudo_kds_clean <- kinomescan_pseudo_kds %>%
  filter(
    classification != "discordant"
  )
```


```{r}
okl_tanimoto_mat <- okl_tanimoto_similarities %>%
  select(id_1, id_2, similarity) %>%
  pivot_wider(
    names_from = id_2, values_from = similarity
  ) %>%
  column_to_rownames("id_1") %>%
  as.matrix()

withr::with_seed(
  42,
  clust <- cluster_fun_eucl(okl_tanimoto_mat)
)

clust_cut <- cutree(clust, k = 8) %>%
  enframe(name = "lspci_id", value = "cluster") %>%
  mutate(across(lspci_id, as.integer)) %>%
  power_left_join(
    okl_compound_info %>%
      select(lspci_id, name),
    by = "lspci_id",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )

cluster_of_interest <- c(8, 7, 3, 4, 6)

clust_cut %>%
  arrange(cluster) %>%
  filter(cluster %in% cluster_of_interest) %>%
  View()
```


```{r}
log_kd_mat <- kinomescan_pseudo_kds_clean %>%
  transmute(
    lspci_id, `DiscoveRx Gene Symbol`,
    across(pseudo_kd, log10)
  ) %>%
  pivot_wider(
    names_from = `DiscoveRx Gene Symbol`, values_from = pseudo_kd
  ) %>%
  column_to_rownames("lspci_id") %>%
  as.matrix()

log_kd_mat_imp <- impute.knn(
  t(log_kd_mat), rng.seed = 42
)[["data"]] %>%
  t()
```

```{r}
log_kd_mat_cor <- log_kd_mat_imp %>%
  t() %>%
  cor(method = "kendall") %>%
  magrittr::extract(clust$labels, clust$labels)

log_kd_mat_cor_pearson <- log_kd_mat_imp %>%
  t() %>%
  cor(method = "pearson") %>%
  magrittr::extract(clust$labels, clust$labels)

log_kd_mat_dist_euclidian <- log_kd_mat_imp %>%
  dist() %>%
  as.matrix() %>%
  magrittr::extract(clust$labels, clust$labels)

withr::with_seed(
  42,
  clust_kd <- cluster_fun_eucl(2 - log_kd_mat_cor)
)

clust_cut_kd <- cutree(clust_kd, k = 8) %>%
  enframe(name = "lspci_id", value = "cluster") %>%
  mutate(across(lspci_id, as.integer)) %>%
  power_left_join(
    okl_compound_info %>%
      select(lspci_id, name),
    by = "lspci_id",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )

```


```{r}
library(lspcheminf)

cluster_cut_structures <- clust_cut %>%
  arrange(cluster) %>%
  # filter(cluster %in% cluster_of_interest) %>%
  mutate(
    inchi = compound_dictionary[["inchi"]][match(as.integer(lspci_id), compound_dictionary[["lspci_id"]])]
  )
```


```{r}
clust_medoids <- clust_cut %>%
  group_by(cluster) %>%
  summarize(
    medoid = {
      message("Processing cluster ", cluster[1])
      total_sims <- okl_tanimoto_mat[as.character(lspci_id), as.character(lspci_id)] %>%
        rowSums() %>%
        sort(decreasing = TRUE)
      message(paste(names(total_sims), signif(total_sims, 3), collapse = " "))
      names(which.max(total_sims))
    },
    .groups = "drop"
  ) %>%
  power_left_join(
    okl_compound_info %>%
      transmute(lspci_id = as.character(lspci_id), name),
    by = c("medoid" = "lspci_id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  power_left_join(
    cluster_cut_structures %>%
      transmute(lspci_id = as.character(lspci_id), inchi),
    by = c("medoid" = "lspci_id"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  )
```

```{r}
pwalk(
  clust_medoids,
  \(medoid, lspci_id, name, inchi, cluster, ...) {
    tmp <- tempfile(fileext = ".svg")
    draw_compound_grid(
      set_names(inchi, ""),
      tmp
    )
    rsvg::rsvg_svg(
      tmp,
      file.path("plots", paste0("structure_similarity_medoid_cluster_", cluster, "_", name, ".svg"))
    )
  }
)

```


```{r}
align_cluster_labels <- function(method1, method2) {
  # Create contingency table
  cont_table <- table(method1, method2)

  # Solve the assignment problem to maximize overlap
  # We use negative because solve_LSAP minimizes cost
  assignment <- clue::solve_LSAP(cont_table, maximum = TRUE)

  # Create mapping from old to new labels
  mapping <- data.frame(
    new_label = 1:length(assignment),
    old_label = assignment
  ) %>%
    arrange(old_label)

  # Return both the mapping and the relabeled clusters
  list(
    mapping = mapping,
    relabeled = mapping$new_label[method2]
  )
}

clusts <- list(
  tanimoto = okl_tanimoto_mat,
  kd_pearson = log_kd_mat_cor_pearson,
  kd_kendall = log_kd_mat_cor,
  kd_euclidian = log_kd_mat_dist_euclidian
) %>%
  imap(
    \(x, y) {
      cur_clust <- withr::with_seed(
        42, {
          # cur_clust <- cluster_fun_eucl(
          #   if (y == "tanimoto") x else 2 - x
          # )
          # d <- as.dist(if (y == "tanimoto") x else 2 - x)
          # if (y == "tanimoto")
          cluster_fun_eucl(x)
          # else {
          #   d <- as.dist(if (y == "kd_euclidian") x else 1 - x)
          #   hclust(
          #     d,
          #     method = "average"
          #   ) %>%
          #     reorder(d, method = "OLO")
          # }
        }
      )
      cur_cut <- cutree(cur_clust, k = 8) %>%
        enframe(name = "lspci_id", value = "cluster") %>%
        mutate(across(lspci_id, as.integer)) %>%
        power_left_join(
          okl_compound_info %>%
            select(lspci_id, name),
          by = "lspci_id",
          check = check_specs(
            unmatched_keys_left = "warn",
            duplicate_keys_right = "warn"
          )
        )
      list(
        clust = cur_clust,
        cut = cur_cut
      )
    }
  ) %>% {
    all_cut <- map(., \(x) x$cut)
    remapped <- map(
      all_cut,
      \(x) {
        x_ <- x
        res <- align_cluster_labels(all_cut[[1]]$cluster, x$cluster)
        x_$cluster <- res$relabeled
        x_
      }
    )
    map2(., remapped, \(x, y) list(clust = x$clust, cut = y))
  }
```


```{r}
coral_map <- syn("syn61680422") %>%
  read_csv()

tanimoto_clust_1_kds <- clusts$tanimoto$cut %>%
  filter(cluster == 1) %>%
  select(lspci_id, name) %>%
  power_inner_join(
    kinomescan_pseudo_kds_clean %>%
      transmute(lspci_id,  `DiscoveRx Gene Symbol`, hgnc_symbol, pseudo_kd),
    by = "lspci_id",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_left = "warn"
    )
  )

p <- tanimoto_clust_1_kds %>%
  select(`DiscoveRx Gene Symbol`, name, pseudo_kd) %>%
  group_by(`DiscoveRx Gene Symbol`) %>%
  filter(any(pseudo_kd < 1000)) %>%
  ungroup() %>%
  pivot_wider(
    names_from = `DiscoveRx Gene Symbol`, values_from = pseudo_kd
  ) %>%
  column_to_rownames("name") %>%
  as.matrix() %>%
  log10() %>%
  Heatmap(
    col = viridisLite::viridis(100) %>% rev(),
    cluster_rows = cluster_fun_eucl,
    cluster_columns = cluster_fun_eucl
  )

withr::with_pdf(
  "plots/tanimoto_cluster_1_kd_hm.pdf",
  draw(p), width = 35, height = 7
)

tanimoto_clust_1_kds %>%
  filter(pseudo_kd < 1000) %>%
  group_by(`DiscoveRx Gene Symbol`) %>%
  summarize(
    n = n(),
    .groups = "drop"
  ) %>%
  power_inner_join(
    coral_map %>%
      select(`DiscoveRx Gene Symbol`, CORAL),
    by = "DiscoveRx Gene Symbol",
    check = check_specs(
      unmatched_keys_left = "info",
      duplicate_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  select(CORAL, n) %>%
  clipr::write_clip()
```



```{r}
all_clust_cuts <- clusts %>%
  map("cut") %>%
  bind_rows(.id = "mat")

mat_compound_info <- okl_compound_info %>%
  # mutate(across(lspci_id, as.character)) %>%
  slice(match(rownames(okl_tanimoto_mat), lspci_id)) %>%
  power_inner_join(
    select(
      all_clust_cuts,
      mat, lspci_id, cluster
    ) %>%
      pivot_wider(
        names_from = mat, values_from = cluster,
        names_prefix = "cluster_"
      ),
    by = "lspci_id",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_left = "warn",
      unmatched_keys_right = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    across(starts_with("cluster_"), \(x) fct_inseq(as.character(x)))
  )

cluster_col_map <- c(`1` = "#E69F00FF", `2` = "#56B4E9FF", `3` = "#009E73FF", `4` = "#F0E442FF",
`5` = "#0072B2FF", `6` = "#D55E00FF", `7` = "#CC79A7FF", `8` = "#999999FF"
)

clust_cut_of_interest <- clust_cut %>%
  mutate(row_id = seq_len(n())) %>%
  filter(cluster %in% cluster_of_interest)

write_csv(
  clust_cut,
  "data/okl_structural_similarity_clusters.csv"
)


cluster_interpretations <- tribble(
  ~cluster, ~interpretation,
  3, "EGFR, VGFR, FLT3...?",
  4, "MEK?",
  6, "Sporines",
  7, "Tyrosine kinase",
  8, "Barasertib"
)
```

```{r}
hm_fun <- \(mat_name, clust_by, part, include_structures = FALSE, ...) {
  message(
    "Processing heatmap for ",
    mat_name,
    " similarity, clustering by ",
    clust_by,
    ", part ",
    part
  )
  cur_mat <- switch(
    mat_name,
    tanimoto = okl_tanimoto_mat,
    kd_pearson = log_kd_mat_cor_pearson,
    kd_kendall = log_kd_mat_cor,
    kd_euclidian = log_kd_mat_dist_euclidian
  )
  cur_clust_info <- clusts[[clust_by]]
  cur_clust <- cur_clust_info$clust
  cur_cut <- cur_clust_info$cut
  dend <- as.dendrogram(cur_clust) %>%
    branches_attr_by_clusters(
      clusters = cur_cut$cluster[cur_clust$order],
      values = cluster_col_map[unique(cur_cut$cluster[cur_clust$order])]
    )

  cluster_anno_colors <- mat_compound_info %>%
    names() %>%
    str_subset(fixed("cluster_")) %>%
    set_names() %>%
    map(\(x) \(x) ggokabeito::palette_okabe_ito(seq_len(8)))

  if (clust_by == "tanimoto" && include_structures)
    structure_anno <- anno_zoom(
      clust_cut_of_interest %>%
        slice(
          match(clust$order, row_id)
        ) %>%
        mutate(across(cluster, \(x) fct_inorder(as.character(x)))) %>%
        split(.$cluster) %>%
        map("row_id"),
      \(index, nm) {
        pushViewport(viewport(xscale = c(0, 1), yscale = c(0, 1)))
        # grid.rect(gp = gpar(fill = "gray95", col = NA))
        # grid.rect(
        #   gp = gpar(
        #     fill = cluster_col_map[nm],
        #     col = NA,
        #     alpha = .5
        #   )
        # )
        grid.text(
          clust_medoids$name[clust_medoids$cluster == nm],
          x = unit(.5, "npc"), y = unit(1, "npc"),
          just = c("center", "top"),
          gp = gpar(fontsize = 8)
        )
        struct <- grImport2::readPicture(
          file.path("plots", paste0("structure_similarity_medoid_cluster_", nm, "_", clust_medoids$name[clust_medoids$cluster == nm], ".svg"))
        )
        grImport2::grid.picture(
          struct,
          x = unit(0, "npc"), y = unit(.5, "npc"),
          just = c("left", "center"),
          width = unit(4, "npc"), height = unit(4, "npc")
        )
        popViewport()
      },
      which = "row", side = "right",
      gap = unit(1, "mm"),
      size = unit(1.5, "cm"), width = unit(3, "cm"),
      link_gp = gpar(fill = "gray95", col = NA)
    )
  else
    structure_anno <- NULL
  row_anno <- createAnnotation(
    mat_compound_info %>%
      select(lspci_id, starts_with("cluster")) %>%
      column_to_rownames("lspci_id"),
    which = "row",
    colors = cluster_anno_colors,
    structures = structure_anno,
    annotation_width = unit(c(if (clust_by == "tanimoto" && include_structures) 30 else NULL, 2, 2, 2, 2), "mm"),
    gap = unit(0, "mm"),
    show_legend = FALSE
  )

  # Reorder annotations
  row_anno@anno_list <- rev(row_anno@anno_list)
  row_anno@anno_size <- rev(row_anno@anno_size)


  col_anno <- createAnnotation(
    mat_compound_info %>%
      select(lspci_id, starts_with("cluster")) %>%
      column_to_rownames("lspci_id"),
    which = "column",
    colors = cluster_anno_colors,
    simple_anno_size = unit(2, "mm")
  )

  mat_processed <- switch(
    part,
    full = cur_mat,
    lower = {
      cur_mat_ <- cur_mat[cur_clust$order, cur_clust$order]
      cur_mat_[upper.tri(cur_mat_)] <- NA
      rev_order <- order(cur_clust$order)
      cur_mat_ <- cur_mat_[rev_order, rev_order]
      cur_mat_
    },
    upper = {
      cur_mat_ <- cur_mat[cur_clust$order, cur_clust$order]
      cur_mat_[lower.tri(cur_mat_)] <- NA
      rev_order <- order(cur_clust$order)
      cur_mat_ <- cur_mat_[rev_order, rev_order]
      cur_mat_
    }
  )
  # browser()
  cur_col_map <- if (mat_name == "tanimoto")
    circlize::colorRamp2(seq(0, .4, length.out = 11), rev(RColorBrewer::brewer.pal(11, "RdBu")))
  else {
    hm_lims <- cur_mat[cur_clust$labels, cur_clust$labels] %>%
      {.[upper.tri(.)]} %>%
      quantile(c(.02, .98)) %>%
      abs() %>%
      max() %>%
      magrittr::multiply_by(c(-1, 1))
    message("Limits ", hm_lims)
    circlize::colorRamp2(seq(hm_lims[1], hm_lims[2], length.out = 11), rev(RColorBrewer::brewer.pal(11, "RdBu")))
  }
  # browser()
  withr::with_pdf(
    NULL,
    Heatmap(
      mat_processed,
      name = switch(
        mat_name,
        tanimoto = "Tanimoto similarity",
        kd_pearson = "Pearson correlation",
        kd_kendall = "Kendall correlation",
        kd_euclidian = "Euclidian distance"
      ),
      col = cur_col_map,
      cluster_rows = dend,
      cluster_columns = dend,
      top_annotation = col_anno,
      right_annotation = row_anno,
      # left_annotation = row_anno,
      # right_annotation = right_anno,
      # show_row_names = FALSE,
      row_labels = mat_compound_info$name,
      show_column_names = FALSE,
      width = unit(.5, "mm") * nrow(mat_processed),
      height = unit(.5, "mm") * nrow(mat_processed),
      row_dend_width = unit(3, "mm"),
      column_dend_height = unit(3, "mm"),
      ...
    ) %>%
      draw()
  )
}

hms <- crossing(
  mat_name = c("tanimoto", "kd_pearson", "kd_kendall"),
  clust_by = c("tanimoto", "kd_pearson", "kd_kendall"),
  part = c("lower", "upper", "full"),
  include_structures = FALSE,
  show_row_names = TRUE
) %>%
  # filter(clust_by == "tanimoto") %>%
  mutate(
    hm = pmap(
      pick(everything()),
      hm_fun
    )
  )

pwalk(
  hms,
  \(hm, mat_name, clust_by, part, ...) {
    wh <- c(
      convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE),
      convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE)
    )
    withr::with_pdf(
      file.path("plots", paste0("compound_similarity_heatmap_hm_", mat_name, "_clust_", clust_by, "_", part, "_with_labels.pdf")),
      draw(hm),
      width = wh[1], height = wh[2]
    )
  }
)

```


```{r}
okl_tanimoto_mat_l <- okl_tanimoto_mat[clust$order, clust$order]
okl_tanimoto_mat_l[upper.tri(okl_tanimoto_mat_l)] <- NA
# Invert ordering again to original
rev_order <- order(clust$order)
okl_tanimoto_mat_l <- okl_tanimoto_mat_l[rev_order, rev_order]

withr::with_pdf(
  NULL,
  hm <- Heatmap(
    okl_tanimoto_mat,
    name = "Tanimoto similarity",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    # col = circlize::colorRamp2(c(0, .2, .4), c("blue", "white", "red")),
    col = circlize::colorRamp2(seq(0, .4, length.out = 11), RColorBrewer::brewer.pal(11, "RdBu")),
    cluster_rows = dend,
    cluster_columns = dend,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * nrow(okl_tanimoto_mat),
    height = unit(.5, "mm") * nrow(okl_tanimoto_mat),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

wh <- c(convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE), convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE))

withr::with_pdf(
  "plots/compound_similarity_heatmap7.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)
```



```{r}
okl_tanimoto_mat_l <- okl_tanimoto_mat[clust_kd$order, clust_kd$order]
okl_tanimoto_mat_l[upper.tri(okl_tanimoto_mat_l)] <- NA
# Invert ordering again to original
rev_order <- order(clust_kd$order)
okl_tanimoto_mat_l <- okl_tanimoto_mat_l[rev_order, rev_order]

withr::with_pdf(
  NULL,
  hm <- Heatmap(
    okl_tanimoto_mat_l,
    name = "Tanimoto similarity",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = circlize::colorRamp2(c(0, .2, .4), c("blue", "white", "red")),
    cluster_rows = dend_kd,
    cluster_columns = dend_kd,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * nrow(okl_tanimoto_mat),
    height = unit(.5, "mm") * nrow(okl_tanimoto_mat),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

wh <- c(convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE), convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE))

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_order.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)
```


```{r}
clust_cut %>%
  filter(cluster == 3) %>%
  pull(name) %>%
  paste(collapse = ", ") %>%
  clipr::write_clip()

```


```{r}
cluster_cut_smiles <- convert_compound_descriptor(
  with(
    cluster_cut_structures,
    set_names(inchi, name)
  ),
  "smiles"
)

cluster_cut_structures_smiles <- cluster_cut_structures %>%
  left_join(
    cluster_cut_smiles %>%
      select(name = names, smiles = compounds),
    by = "name"
  )
cluster_cut_structures_mcs <- cluster_cut_structures_smiles %>%
  filter(cluster != 6) %>%
  group_by(cluster) %>%
  summarize(
    mcs = {
    message("Processing cluster ", cluster[1])
    maximum_common_substructure(
      with(
        cur_data(),
        compounds(
          set_names(smiles, name),
          descriptor = "smiles"
        )
      )
    )
    },
    .groups = "drop"
  ) %>%
  # Manually add back sporins again
  bind_rows(
    cluster_cut_structures_smiles %>%
      filter(name == "STAUROSPORINE") %>%
      select(cluster, mcs = smiles)
  )

```

```{r}
draw_compound_grid(
  with(
    cluster_cut_structures_mcs,
    compounds(
      set_names(mcs, cluster),
      descriptor = "smiles"
    )
  ),
  file.path("plots", paste0("structural_similarity_clusters_mcs.svg"))
  # draw_args = list(subImgSize = c(300, 300))
  # common_core = compounds(common_substructure, descriptor = "smiles")
)

```


```{r}
group_walk(
  group_by(cluster_cut_structures, cluster),
  \(x, y) {
    message("Processing cluster ", y$cluster)
    # converted <- convert_compound_descriptor(
    #   with(
    #     x,
    #     set_names(inchi, name)
    #   ),
    #   "smiles"
    # )
    # common_substructure <- maximum_common_substructure(
    #   compounds(
    #     with(
    #       converted,
    #       set_names(compounds, names)
    #     ),
    #     descriptor = "smiles"
    #   )
    # )
    draw_compound_grid(
      with(
        x,
        set_names(inchi, name)
      ),
      file.path("plots", paste0("structural_similarity_cluster_", y$cluster, "_structures.svg")),
      draw_args = list(subImgSize = c(300, 300))
      # common_core = compounds(common_substructure, descriptor = "smiles")
    )
  }
)


```

```{r}
clust_lspci_order <- clust$labels[clust$order]

hm_lims <- log_kd_mat_cor_pearson[clust$labels, clust$labels] %>%
  {.[upper.tri(.)]} %>%
  quantile(c(.02, .98)) %>%
  abs() %>%
  max() %>%
  magrittr::multiply_by(c(-1, 1))

col_fun_cor <- circlize::colorRamp2(c(hm_lims[1], 0, hm_lims[2]), c("blue", "white", "red"))

withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor_pearson[clust$labels, clust$labels],
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend,
    cluster_columns = dend,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

wh <- c(convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE), convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE))

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor_pearson.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

log_kd_mat_cor_pearson_l <- log_kd_mat_cor_pearson[clust_lspci_order, clust_lspci_order]
log_kd_mat_cor_pearson_l[lower.tri(log_kd_mat_cor_pearson_l)] <- NA
# Invert ordering again to original
rev_order <- order(clust$order)
log_kd_mat_cor_pearson_l <- log_kd_mat_cor_pearson_l[clust$labels, clust$labels]


withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor_pearson_l,
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend,
    cluster_columns = dend,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor_pearson_l.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

```


```{r}
log_kd_mat_cor <- log_kd_mat_imp %>%
  t() %>%
  cor(method = "kendall")

log_kd_mat_cor_pearson <- log_kd_mat_imp %>%
  t() %>%
  cor(method = "pearson")

clust_lspci_order <- clust$labels[clust$order]

hm_lims <- log_kd_mat_cor[clust$labels, clust$labels] %>%
  {.[upper.tri(.)]} %>%
  quantile(c(.02, .98)) %>%
  abs() %>%
  max() %>%
  magrittr::multiply_by(c(-1, 1))

col_fun_cor <- circlize::colorRamp2(c(hm_lims[1], 0, hm_lims[2]), c("blue", "white", "red"))

withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor[clust$labels, clust$labels],
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend,
    cluster_columns = dend,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

wh <- c(convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE), convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE))

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

log_kd_mat_cor_l <- log_kd_mat_cor[clust_lspci_order, clust_lspci_order]
log_kd_mat_cor_l[lower.tri(log_kd_mat_cor_l)] <- NA
# Invert ordering again to original
rev_order <- order(clust$order)
log_kd_mat_cor_l <- log_kd_mat_cor_l[clust$labels, clust$labels]


withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor_l,
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend,
    cluster_columns = dend,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor_l.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

```


```{r}
clust_lspci_order <- clust_kd$labels[clust_kd$order]

hm_lims <- log_kd_mat_cor[clust_kd$labels, clust_kd$labels] %>%
  {.[upper.tri(.)]} %>%
  quantile(c(.02, .98)) %>%
  abs() %>%
  max() %>%
  magrittr::multiply_by(c(-1, 1))

col_fun_cor <- circlize::colorRamp2(c(hm_lims[1], 0, hm_lims[2]), c("blue", "white", "red"))

withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor[clust_kd$labels, clust_kd$labels],
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend_kd,
    cluster_columns = dend_kd,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

wh <- c(convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE), convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE))

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor_kd_order.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

log_kd_mat_cor_l <- log_kd_mat_cor[clust_lspci_order, clust_lspci_order]
log_kd_mat_cor_l[lower.tri(log_kd_mat_cor_l)] <- NA
# Invert ordering again to original
rev_order <- order(clust_kd$order)
log_kd_mat_cor_l <- log_kd_mat_cor_l[clust_kd$labels, clust_kd$labels]


withr::with_pdf(
  NULL,
  hm <- Heatmap(
    log_kd_mat_cor_l,
    name = "Pearson correlation",
    # col = circlize::colorRamp2(c(0, .1, .2, .3, .4), rev(RColorBrewer::brewer.pal(5, "RdBu"))),
    col = col_fun_cor,
    cluster_rows = dend_kd,
    cluster_columns = dend_kd,
    top_annotation = col_anno,
    right_annotation = row_anno,
    # left_annotation = row_anno,
    # right_annotation = right_anno,
    show_row_names = FALSE,
    show_column_names = FALSE,
    width = unit(.5, "mm") * length(clust_lspci_order),
    height = unit(.5, "mm") * length(clust_lspci_order),
    row_dend_width = unit(3, "mm"),
    column_dend_height = unit(3, "mm")
  ) %>%
    draw()
)

# pheatmap(log_kd_mat_cor[clust_lspci_order, clust_lspci_order], cluster_rows = FALSE, cluster_cols = FALSE)

withr::with_pdf(
  "plots/compound_similarity_heatmap_kd_cor_l_kd_order.pdf",
  draw(hm),
  width = wh[1], height = wh[2]
)

```



```{r}

log_kd_diff_mat <- dist(log_kd_mat_imp)

log_kd_diff_df <- as.matrix(log_kd_diff_mat) %>%
  as.data.frame() %>%
  rownames_to_column("lspci_id_1") %>%
  pivot_longer(
    -lspci_id_1, names_to = "lspci_id_2", values_to = "kd_distance"
  ) %>%
  mutate(
    across(starts_with("lspci_id"), as.integer)
  )

# Tanimoto similarities only contain OKL compounds, Kd similarities still all compounds
# therefore inner_join with some missing matches
kd_diff_vs_sim <- log_kd_diff_df %>%
  power_inner_join(
    okl_tanimoto_similarities %>%
      select(lspci_id_1 = id_1, lspci_id_2 = id_2, starts_with("name_"), similarity),
    by = c("lspci_id_1", "lspci_id_2"),
    check = check_specs(
      # unmatched_keys_left = "warn",
      duplicate_keys_left = "warn",
      unmatched_keys_right = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  arrange(
    match(lspci_id_1, rownames(log_kd_mat))
  ) %>%
  mutate(
    across(
      c(name_1, name_2),
      \(x) factor(x, levels = unique(name_1))
    )
  )

kd_diff_vs_sim_upper <- kd_diff_vs_sim %>%
  filter(
    as.integer(name_1) > as.integer(name_2)
  ) %>%
  mutate(
    density = MASS::kde2d(
      similarity, kd_distance,
      n = 100
    ) %>%
    fields::interp.surface(
      cbind(similarity, kd_distance)
    )
  ) %>%
  power_left_join(
    clust_cut %>%
      select(lspci_id_1 = lspci_id, cluster_1 = cluster),
    by = "lspci_id_1",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  power_left_join(
    clust_cut %>%
      select(lspci_id_2 = lspci_id, cluster_2 = cluster),
    by = "lspci_id_2",
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    cluster_both = if_else(cluster_1 == cluster_2, as.character(cluster_1), "different")
  )
```

```{r}
kd_diff_vs_sim_lm <- lm(
  kd_distance ~ similarity,
  data = kd_diff_vs_sim_upper
)
p <- kd_diff_vs_sim_upper %>%
  arrange(density) %>%
  ggplot(
    aes(
      similarity, kd_distance, color = density
    )
  ) +
  ggrastr::rasterize(geom_point(
    shape = 16, alpha = .5, size = 1
  ), dpi = 300) +
  scale_color_viridis_c() +
  labs(
    x = "Tanimoto similarity\nMorgan fingerprints",
    y = "RMS difference log10(pseudo Kd)"
  )

ggsave(
  "plots/kd_diff_vs_structural_sim.pdf", p,
  width = 4, height = 3
)

p <- kd_diff_vs_sim_upper %>%
  mutate(
    cluster_both = factor(cluster_both, levels = c("different", as.character(sort(unique(cluster_1)))))
  ) %>%
  filter(
    cluster_1 %in% cluster_of_interest | cluster_2 %in% cluster_of_interest
  ) %>%
  arrange(desc(cluster_both == "different")) %>%
  # filter(cluster_both %in% as.character(cluster_of_interest)) %>%
  # arrange(cluster_both) %>%
  ggplot(
    aes(
      similarity, kd_distance, color = cluster_both
    )
  ) +
  ggrastr::rasterize(geom_point(
    shape = 16, alpha = .8, size = 1
  ), dpi = 300) +
  ggokabeito::scale_color_okabe_ito() +
  labs(
    x = "Tanimoto similarity\nMorgan fingerprints",
    y = "RMS difference log10(pseudo Kd)"
  )

ggsave(
  "plots/kd_diff_vs_structural_sim_cluster_color.pdf", p,
  width = 4, height = 3
)



```



```{r}
synStoreMany(
  c("data/okl_structural_similarity_clusters.csv"),
  parentId = "syn18508401",
  forceVersion = FALSE
)

```

## Plotting selected Kd cluster targets

```{r}
selected_kd_clusters <- list(
  pi3k_mtor = c(
    "TORIN1", "GEDATOLISIB", "PF-04691502", "PI-103", "AZD-8055", "DACTOLISIB", "APITOLISIB"
  ),
  cdks = c(
    "LY-2090314", "PHA-793887", "RG-547", "BMS-387032", "ALVOCIDIB", "AT-7519"
  ),
  akt_rock = c(
    "GSK-690693", "GSK-269962A", "Y-27632", "FASUDIL", "Y-39983", "A-674563", "SB-7720770B", "PHA-767491"
  ),
  egfr = c(
    "RK-24466", "IBRUTINIB", "SAPITINIB", "CANERTINIB", "ERLOTINIB", "CUDC-101", "GEFITINIB", "AFATINIB", "DACOMITINIB", "NERATINIB", "AC-480", "FALNIDAMOL", "LAPATINIB", "TAK-285", "CP-724714", "SELUMETINIB", "BI-2536"
  ),
  dge_cluster_1 = c(
    "H-89", "DOVITINIB", "TAE-684", "SUNITINIB", "KW-2449", "NINTEDANIB", "FEDRATINIB"
  ),
  dge_cluster_2 = c(
    "TOFACITINIB", "LAPATINIB", "IMATINIB", "GEFITINIB",
    "ERLOTINIB", "DASATINIB", "AXITINIB"
  )
) %>%
  map(rev)

# Verify that all names are in kinomescan_pseudo_kds_clean
map(selected_kd_clusters, \(x) setdiff(x, unique(kinomescan_pseudo_kds_clean$name)))


```

```{r}
# Create heatmaps for selected drug clusters
selected_kd_heatmaps <- imap(
  selected_kd_clusters,
  \(drugs, cluster_name) {
    drugs <- intersect(drugs, unique(kinomescan_pseudo_kds_clean$name))
    # Filter Kd data for selected drugs and kinases with at least one strong hit
    kd_data <- kinomescan_pseudo_kds_clean %>%
      filter(
        name %in% drugs,
        classification != "discordant"
      ) %>%
      group_by(`DiscoveRx Gene Symbol`) %>%
      filter(any(pseudo_kd < 1000)) %>%
      ungroup()

    # Create matrix for heatmap
    kd_mat <- kd_data %>%
      select(name, `DiscoveRx Gene Symbol`, pseudo_kd) %>%
      pivot_wider(
        names_from = `DiscoveRx Gene Symbol`,
        values_from = pseudo_kd
      ) %>%
      column_to_rownames("name") %>%
      as.matrix() %>%
      log10() %>% {
        .[drugs, ]
      }

    # Remove columns with more than 80% missing values
    kd_mat <- kd_mat[, colMeans(is.na(kd_mat)) <= 0.8]

    # Create heatmap
    withr::with_pdf(
      NULL,
      p <- Heatmap(
        kd_mat,
        name = "log10(Kd)",
        col = viridisLite::viridis(100) %>% rev(),
        cluster_rows = FALSE,
        cluster_columns = cluster_fun_eucl,
        column_names_rot = 45,
        row_names_side = "left",
        width = unit(5, "mm") * ncol(kd_mat),
        height = unit(5, "mm") * nrow(kd_mat),
      ) %>%
        draw()
    )
    p
  }
)


iwalk(
  selected_kd_heatmaps,
  \(hm, cluster_name) {
    wh <- c(
      convertX(ComplexHeatmap:::width(hm), "inch", valueOnly = TRUE),
      convertY(ComplexHeatmap:::height(hm), "inch", valueOnly = TRUE)
    )
    withr::with_pdf(
      file.path("plots", paste0("kd_cluster_heatmap_", cluster_name, ".pdf")),
      draw(hm),
      width = wh[1], height = wh[2]
    )
  }
)
```

